var e;e||(e=typeof Module !== 'undefined' ? Module : {});e.ma||(e.ma=0,e.lb=0);e.ma++;
(function(a){function b(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onprogress=function(c){var f=b;c.total&&(f=c.total);if(c.loaded){d.v?e.O[a].loaded=c.loaded:(d.v=!0,e.O||(e.O={}),e.O[a]={loaded:c.loaded,total:f});var g=f=c=0,h;for(h in e.O){var q=e.O[h];c+=q.total;f+=q.loaded;g++}c=Math.ceil(c*e.ma/g);e.setStatus&&e.setStatus("Downloading data... ("+f+"/"+c+")")}else!e.O&&e.setStatus&&e.setStatus("Downloading data...")};d.onerror=function(){throw Error("NetworkError for: "+
a);};d.onload=function(){if(200==d.status||304==d.status||206==d.status||0==d.status&&d.response)c(d.response);else throw Error(d.statusText+" : "+d.responseURL);};d.send(null)}function c(){function b(a,b,c,d){this.start=a;this.end=b;this.gb=c;this.audio=d}function c(c){e.lb++;if(!c)throw"Loading data file failed."+Error().stack;if(!(c instanceof ArrayBuffer))throw"bad input to processPackageData"+Error().stack;c=new Uint8Array(c);e.SPLIT_MEMORY&&e.printErr("warning: you should run the file packager with --no-heap-copy when SPLIT_MEMORY is used, otherwise copying into the heap may fail due to the splitting");
var d=e.getMemory(c.length);e.HEAPU8.set(c,d);b.prototype.eb=e.HEAPU8.subarray(d,d+c.length);c=a.files;for(d=0;d<c.length;++d)b.prototype.requests[c[d].filename].onload();e.removeRunDependency("datafile_bin/appplex.data")}e.FS_createPath("/","shaders",!0,!0);e.FS_createPath("/shaders","freetype-gl",!0,!0);e.FS_createPath("/","tex",!0,!0);e.FS_createPath("/tex","skybx",!0,!0);b.prototype={requests:{},open:function(a,b){this.name=b;this.requests[b]=this;e.addRunDependency("fp "+this.name)},onload:function(){this.finish(this.eb.subarray(this.start,
this.end))},finish:function(a){e.FS_createDataFile(this.name,null,a,!0,!0,!0);e.removeRunDependency("fp "+this.name);this.requests[this.name]=null}};for(var d=a.files,f=0;f<d.length;++f)(new b(d[f].start,d[f].end,d[f].gb,d[f].audio)).open("GET",d[f].filename);e.addRunDependency("datafile_bin/appplex.data");e.Va||(e.Va={});e.Va["bin/appplex.data"]={Hd:!1};h?(c(h),h=null):g=c}if("object"===typeof window)window.encodeURIComponent(window.location.pathname.toString().substring(0,window.location.pathname.toString().lastIndexOf("/"))+
"/");else if("undefined"!==typeof location)encodeURIComponent(location.pathname.toString().substring(0,location.pathname.toString().lastIndexOf("/"))+"/");else throw"using preloaded data can only be done on a web page or in a web worker";"function"!==typeof e.locateFilePackage||e.locateFile||(e.locateFile=e.locateFilePackage,e.printErr("warning: you defined Module.locateFilePackage, that has been renamed to Module.locateFile (using your locateFilePackage for now)"));var d="function"===typeof e.locateFile?
e.locateFile("appplex.data"):(e.filePackagePrefixURL||"")+"appplex.data",f=a.Nd,g=null,h=e.getPreloadedPackage?e.getPreloadedPackage(d,f):null;h||b(d,f,function(a){g?(g(a),g=null):h=a});e.calledRun?c():(e.preRun||(e.preRun=[]),e.preRun.push(c))})({files:[{audio:0,start:0,crunched:0,end:0,filename:"/dummy-runtime-file"},{audio:0,start:0,crunched:0,end:447604,filename:"/res-file"},{audio:0,start:447604,crunched:0,end:448831,filename:"/shaders/3d-globe-outline.fsh"},{audio:0,start:448831,crunched:0,
end:449675,filename:"/shaders/3d-globe-outline.vsh"},{audio:0,start:449675,crunched:0,end:449866,filename:"/shaders/basic_tex.fsh"},{audio:0,start:449866,crunched:0,end:450124,filename:"/shaders/basic_tex.vsh"},{audio:0,start:450124,crunched:0,end:450483,filename:"/shaders/conv-rgb-2-u-420.fsh"},{audio:0,start:450483,crunched:0,end:450841,filename:"/shaders/conv-rgb-2-v-420.fsh"},{audio:0,start:450841,crunched:0,end:451201,filename:"/shaders/conv-rgb-2-y-420.fsh"},{audio:0,start:451201,crunched:0,
end:451459,filename:"/shaders/conv-rgb-2-yuv-420.vsh"},{audio:0,start:451459,crunched:0,end:451583,filename:"/shaders/c_o.fsh"},{audio:0,start:451583,crunched:0,end:451738,filename:"/shaders/c_o.vsh"},{audio:0,start:451738,crunched:0,end:451846,filename:"/shaders/globe-border.fsh"},{audio:0,start:451846,crunched:0,end:452001,filename:"/shaders/globe-border.vsh"},{audio:0,start:452001,crunched:0,end:452108,filename:"/shaders/globe-dot.fsh"},{audio:0,start:452108,crunched:0,end:452263,filename:"/shaders/globe-dot.vsh"},
{audio:0,start:452263,crunched:0,end:452560,filename:"/shaders/globe-spike-base.fsh"},{audio:0,start:452560,crunched:0,end:452874,filename:"/shaders/globe-spike-base.vsh"},{audio:0,start:452874,crunched:0,end:453027,filename:"/shaders/globe-spike.fsh"},{audio:0,start:453027,crunched:0,end:454044,filename:"/shaders/globe-spike.vsh"},{audio:0,start:454044,crunched:0,end:454390,filename:"/shaders/hot-spot-lines.fsh"},{audio:0,start:454390,crunched:0,end:455893,filename:"/shaders/hot-spot-lines.vsh"},
{audio:0,start:455893,crunched:0,end:457880,filename:"/shaders/ldo-test.fsh"},{audio:0,start:457880,crunched:0,end:458591,filename:"/shaders/ldo-test.vsh"},{audio:0,start:458591,crunched:0,end:458899,filename:"/shaders/sky-box.fsh"},{audio:0,start:458899,crunched:0,end:459409,filename:"/shaders/sky-box.vsh"},{audio:0,start:459409,crunched:0,end:461799,filename:"/shaders/freetype-gl/v3f-t2f-c4f.frag"},{audio:0,start:461799,crunched:0,end:464174,filename:"/shaders/freetype-gl/v3f-t2f-c4f.vert"},{audio:0,
start:464174,crunched:0,end:555734,filename:"/tex/detail-tex.png"},{audio:0,start:555734,crunched:0,end:562904,filename:"/tex/line-2.png"},{audio:0,start:562904,crunched:0,end:564819,filename:"/tex/line.png"},{audio:0,start:564819,crunched:0,end:567623,filename:"/tex/trail-2.png"},{audio:0,start:567623,crunched:0,end:570417,filename:"/tex/trail.png"},{audio:0,start:570417,crunched:0,end:598665,filename:"/tex/skybx/skybx-negx.png"},{audio:0,start:598665,crunched:0,end:609298,filename:"/tex/skybx/skybx-negy.png"},
{audio:0,start:609298,crunched:0,end:638416,filename:"/tex/skybx/skybx-negz.png"},{audio:0,start:638416,crunched:0,end:649653,filename:"/tex/skybx/skybx-posx.png"},{audio:0,start:649653,crunched:0,end:660121,filename:"/tex/skybx/skybx-posy.png"},{audio:0,start:660121,crunched:0,end:681152,filename:"/tex/skybx/skybx-posz.png"}],remote_package_size:681152,package_uuid:"13547724-e5ab-4ece-a724-00e64b32bdbb"});var aa={},k;for(k in e)e.hasOwnProperty(k)&&(aa[k]=e[k]);e.arguments=[];e.thisProgram="./this.program";
e.quit=function(a,b){throw b;};e.preRun=[];e.postRun=[];var ba=!1,l=!1,m=!1,ca=!1;if(e.ENVIRONMENT)if("WEB"===e.ENVIRONMENT)ba=!0;else if("WORKER"===e.ENVIRONMENT)l=!0;else if("NODE"===e.ENVIRONMENT)m=!0;else if("SHELL"===e.ENVIRONMENT)ca=!0;else throw Error("Module['ENVIRONMENT'] value is not valid. must be one of: WEB|WORKER|NODE|SHELL.");else ba="object"===typeof window,l="function"===typeof importScripts,m="object"===typeof process&&"function"===typeof require&&!ba&&!l,ca=!ba&&!m&&!l;
if(m){var da,ea;e.read=function(a,b){da||(da=require("fs"));ea||(ea=require("path"));a=ea.normalize(a);a=da.readFileSync(a);return b?a:a.toString()};e.readBinary=function(a){a=e.read(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a};1<process.argv.length&&(e.thisProgram=process.argv[1].replace(/\\/g,"/"));e.arguments=process.argv.slice(2);"undefined"!==typeof module&&(module.exports=e);process.on("uncaughtException",function(a){if(!(a instanceof fa))throw a;});process.on("unhandledRejection",
function(){process.exit(1)});e.inspect=function(){return"[Emscripten Module object]"}}else if(ca)"undefined"!=typeof read&&(e.read=function(a){return read(a)}),e.readBinary=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?e.arguments=scriptArgs:"undefined"!=typeof arguments&&(e.arguments=arguments),"function"===typeof quit&&(e.quit=function(a){quit(a)});else if(ba||l)e.read=function(a){var b=
new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},l&&(e.readBinary=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),e.readAsync=function(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=function(){200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)},"undefined"!=typeof arguments&&(e.arguments=arguments),e.setWindowTitle=
function(a){document.title=a};e.print="undefined"!==typeof console?console.log.bind(console):"undefined"!==typeof print?print:null;e.printErr="undefined"!==typeof printErr?printErr:"undefined"!==typeof console&&console.warn.bind(console)||e.print;e.print=e.print;e.printErr=e.printErr;for(k in aa)aa.hasOwnProperty(k)&&(e[k]=aa[k]);aa=void 0;function ha(a){assert(!ia);var b=r;r=r+a+15&-16;return b}function ja(a){var b;b||(b=16);return Math.ceil(a/b)*b}
function ka(a){la||(la={});la[a]||(la[a]=1,e.printErr(a))}var la,ma=0;function assert(a,b){a||t("Assertion failed: "+b)}function na(a){if("number"===typeof a){var b=!0;var c=a}else b=!1,c=a.length;var d=("function"===typeof u?u:ha)(Math.max(c,1));if(b){a=d;assert(0==(d&3));for(b=d+(c&-4);a<b;a+=4)w[a>>2]=0;for(b=d+c;a<b;)oa[a++>>0]=0;return d}a.subarray||a.slice?z.set(a,d):z.set(new Uint8Array(a),d);return d}
function A(a,b){if(0===b||!a)return"";for(var c=0,d,f=0;;){d=z[a+f>>0];c|=d;if(0==d&&!b)break;f++;if(b&&f==b)break}b||(b=f);d="";if(128>c){for(;0<b;)c=String.fromCharCode.apply(String,z.subarray(a,a+Math.min(b,1024))),d=d?d+c:c,a+=1024,b-=1024;return d}return pa(z,a)}var qa="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function pa(a,b){for(var c=b;a[c];)++c;if(16<c-b&&a.subarray&&qa)return qa.decode(a.subarray(b,c));for(c="";;){var d=a[b++];if(!d)return c;if(d&128){var f=a[b++]&63;if(192==(d&224))c+=String.fromCharCode((d&31)<<6|f);else{var g=a[b++]&63;if(224==(d&240))d=(d&15)<<12|f<<6|g;else{var h=a[b++]&63;if(240==(d&248))d=(d&7)<<18|f<<12|g<<6|h;else{var q=a[b++]&63;if(248==(d&252))d=(d&3)<<24|f<<18|g<<12|h<<6|q;else{var n=a[b++]&63;d=(d&1)<<30|f<<24|g<<18|h<<12|q<<6|n}}}65536>d?c+=String.fromCharCode(d):(d-=
65536,c+=String.fromCharCode(55296|d>>10,56320|d&1023))}}else c+=String.fromCharCode(d)}}
function B(a,b,c,d){if(!(0<d))return 0;var f=c;d=c+d-1;for(var g=0;g<a.length;++g){var h=a.charCodeAt(g);55296<=h&&57343>=h&&(h=65536+((h&1023)<<10)|a.charCodeAt(++g)&1023);if(127>=h){if(c>=d)break;b[c++]=h}else{if(2047>=h){if(c+1>=d)break;b[c++]=192|h>>6}else{if(65535>=h){if(c+2>=d)break;b[c++]=224|h>>12}else{if(2097151>=h){if(c+3>=d)break;b[c++]=240|h>>18}else{if(67108863>=h){if(c+4>=d)break;b[c++]=248|h>>24}else{if(c+5>=d)break;b[c++]=252|h>>30;b[c++]=128|h>>24&63}b[c++]=128|h>>18&63}b[c++]=128|
h>>12&63}b[c++]=128|h>>6&63}b[c++]=128|h&63}}b[c]=0;return c-f}function ra(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:2097151>=d?b+4:67108863>=d?b+5:b+6}return b}"undefined"!==typeof TextDecoder&&new TextDecoder("utf-16le");function sa(a){var b=ra(a)+1,c=ta(b);B(a,oa,c,b);return c}var buffer,oa,z,ua,wa,w,xa,C,D;
function ya(){e.HEAP8=oa=new Int8Array(buffer);e.HEAP16=ua=new Int16Array(buffer);e.HEAP32=w=new Int32Array(buffer);e.HEAPU8=z=new Uint8Array(buffer);e.HEAPU16=wa=new Uint16Array(buffer);e.HEAPU32=xa=new Uint32Array(buffer);e.HEAPF32=C=new Float32Array(buffer);e.HEAPF64=D=new Float64Array(buffer)}var za,r,ia,Aa,Ba,Ca,Da,Fa;za=r=Aa=Ba=Ca=Da=Fa=0;ia=!1;
function Ga(){t("Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value "+Ha+", (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which allows increasing the size at runtime, or (3) if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 ")}var Ia=e.TOTAL_STACK||5242880,Ha=e.TOTAL_MEMORY||67108864;Ha<Ia&&e.printErr("TOTAL_MEMORY should be larger than TOTAL_STACK, was "+Ha+"! (TOTAL_STACK="+Ia+")");
e.buffer?buffer=e.buffer:("object"===typeof WebAssembly&&"function"===typeof WebAssembly.Memory?(e.wasmMemory=new WebAssembly.Memory({initial:Ha/65536,maximum:Ha/65536}),buffer=e.wasmMemory.buffer):buffer=new ArrayBuffer(Ha),e.buffer=buffer);ya();w[0]=1668509029;ua[1]=25459;if(115!==z[2]||99!==z[3])throw"Runtime error: expected the system to be little-endian!";
function Ja(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b();else{var c=b.i;"number"===typeof c?void 0===b.ea?e.dynCall_v(c):e.dynCall_vi(c,b.ea):c(void 0===b.ea?null:b.ea)}}}var Ka=[],La=[],Ma=[],Na=[],Oa=[],Pa=!1;function Qa(){var a=e.preRun.shift();Ka.unshift(a)}var Ra=0,Sa=null,Ta=null;function Ua(){Ra++;e.monitorRunDependencies&&e.monitorRunDependencies(Ra)}
function Va(){Ra--;e.monitorRunDependencies&&e.monitorRunDependencies(Ra);if(0==Ra&&(null!==Sa&&(clearInterval(Sa),Sa=null),Ta)){var a=Ta;Ta=null;a()}}e.preloadedImages={};e.preloadedAudios={};function Wa(a){return String.prototype.startsWith?a.startsWith("data:application/octet-stream;base64,"):0===a.indexOf("data:application/octet-stream;base64,")}
(function(){function a(){try{if(e.wasmBinary)return new Uint8Array(e.wasmBinary);if(e.readBinary)return e.readBinary(f);throw"on the web, we need the wasm binary to be preloaded and set on Module['wasmBinary']. emcc.py will do that for you when generating HTML (but not JS)";}catch(v){t(v)}}function b(){return e.wasmBinary||!ba&&!l||"function"!==typeof fetch?new Promise(function(b){b(a())}):fetch(f,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+f+
"'";return a.arrayBuffer()}).catch(function(){return a()})}function c(a){function c(a){q=a.exports;if(q.memory){a=q.memory;var b=e.buffer;a.byteLength<b.byteLength&&e.printErr("the new buffer in mergeMemory is smaller than the previous one. in native wasm, we should grow memory here");b=new Int8Array(b);(new Int8Array(a)).set(b);e.buffer=buffer=a;ya()}e.asm=q;e.usingWasm=!0;Va()}function d(a){c(a.instance)}function g(a){b().then(function(a){return WebAssembly.instantiate(a,h)}).then(a).catch(function(a){e.printErr("failed to asynchronously prepare wasm: "+
a);t(a)})}if("object"!==typeof WebAssembly)return e.printErr("no native wasm support detected"),!1;if(!(e.wasmMemory instanceof WebAssembly.Memory))return e.printErr("no native wasm Memory in use"),!1;a.memory=e.wasmMemory;h.global={NaN:NaN,Infinity:Infinity};h["global.Math"]=Math;h.env=a;Ua();if(e.instantiateWasm)try{return e.instantiateWasm(h,c)}catch(va){return e.printErr("Module.instantiateWasm callback failed with error: "+va),!1}e.wasmBinary||"function"!==typeof WebAssembly.instantiateStreaming||
Wa(f)||"function"!==typeof fetch?g(d):WebAssembly.instantiateStreaming(fetch(f,{credentials:"same-origin"}),h).then(d).catch(function(a){e.printErr("wasm streaming compile failed: "+a);e.printErr("falling back to ArrayBuffer instantiation");g(d)});return{}}var d="appplex.wast",f="appplex.wasm",g="appplex.temp.asm.js";"function"===typeof e.locateFile&&(Wa(d)||(d=e.locateFile(d)),Wa(f)||(f=e.locateFile(f)),Wa(g)||(g=e.locateFile(g)));var h={global:null,env:null,asm2wasm:{"f64-rem":function(a,b){return a%
b},"debugger":function(){debugger}},parent:e},q=null;e.asmPreload=e.asm;var n=e.reallocBuffer;e.reallocBuffer=function(a){if("asmjs"===p)var b=n(a);else a:{var c=e.usingWasm?65536:16777216;0<a%c&&(a+=c-a%c);c=e.buffer.byteLength;if(e.usingWasm)try{b=-1!==e.wasmMemory.grow((a-c)/65536)?e.buffer=e.wasmMemory.buffer:null;break a}catch(x){b=null;break a}b=void 0}return b};var p="";e.asm=function(a,b){if(!b.table){a=e.wasmTableSize;void 0===a&&(a=1024);var d=e.wasmMaxTableSize;b.table="object"===typeof WebAssembly&&
"function"===typeof WebAssembly.Table?void 0!==d?new WebAssembly.Table({initial:a,maximum:d,element:"anyfunc"}):new WebAssembly.Table({initial:a,element:"anyfunc"}):Array(a);e.wasmTable=b.table}b.memoryBase||(b.memoryBase=e.STATIC_BASE);b.tableBase||(b.tableBase=0);(b=c(b))||t("no binaryen method succeeded. consider enabling more options, like interpreting, if you want that: https://github.com/kripken/emscripten/wiki/WebAssembly#binaryen-methods");return b}})();za=1024;r=za+66928;
La.push({i:function(){Xa()}},{i:function(){Ya()}},{i:function(){Za()}},{i:function(){$a()}},{i:function(){ab()}},{i:function(){bb()}},{i:function(){cb()}},{i:function(){db()}},{i:function(){eb()}},{i:function(){fb()}},{i:function(){gb()}},{i:function(){hb()}},{i:function(){ib()}},{i:function(){jb()}},{i:function(){kb()}},{i:function(){lb()}},{i:function(){mb()}},{i:function(){nb()}},{i:function(){ob()}});e.STATIC_BASE=za;e.STATIC_BUMP=66928;r+=16;function pb(){return!!pb.v}
var E={L:1,C:2,pd:3,kc:4,H:5,Aa:6,Db:7,Ic:8,ba:9,Rb:10,va:11,zd:11,Za:12,ia:13,cc:14,Uc:15,ja:16,wa:17,Ad:18,la:19,ya:20,U:21,h:22,Dc:23,Ya:24,K:25,wd:26,dc:27,Qc:28,da:29,md:30,wc:31,dd:32,$b:33,jd:34,Mc:42,hc:43,Sb:44,nc:45,oc:46,pc:47,vc:48,xd:49,Gc:50,mc:51,Xb:35,Jc:37,Jb:52,Mb:53,Bd:54,Ec:55,Nb:56,Ob:57,Yb:35,Pb:59,Sc:60,Hc:61,td:62,Rc:63,Nc:64,Oc:65,ld:66,Kc:67,Gb:68,qd:69,Tb:70,ed:71,yc:72,ac:73,Lb:74,Zc:76,Kb:77,kd:78,qc:79,rc:80,uc:81,tc:82,sc:83,Tc:38,za:39,zc:36,ka:40,$c:95,cd:96,Wb:104,
Fc:105,Hb:97,hd:91,Xc:88,Pc:92,nd:108,Vb:111,Eb:98,Ub:103,Cc:101,Ac:100,ud:110,ec:112,fc:113,jc:115,Ib:114,Zb:89,xc:90,gd:93,od:94,Fb:99,Bc:102,lc:106,Vc:107,vd:109,yd:87,bc:122,rd:116,Yc:95,Lc:123,ic:84,ad:75,Qb:125,Wc:131,bd:130,sd:86},qb={0:"Success",1:"Not super-user",2:"No such file or directory",3:"No such process",4:"Interrupted system call",5:"I/O error",6:"No such device or address",7:"Arg list too long",8:"Exec format error",9:"Bad file number",10:"No children",11:"No more processes",12:"Not enough core",
13:"Permission denied",14:"Bad address",15:"Block device required",16:"Mount device busy",17:"File exists",18:"Cross-device link",19:"No such device",20:"Not a directory",21:"Is a directory",22:"Invalid argument",23:"Too many open files in system",24:"Too many open files",25:"Not a typewriter",26:"Text file busy",27:"File too large",28:"No space left on device",29:"Illegal seek",30:"Read only file system",31:"Too many links",32:"Broken pipe",33:"Math arg out of domain of func",34:"Math result not representable",
35:"File locking deadlock error",36:"File or path name too long",37:"No record locks available",38:"Function not implemented",39:"Directory not empty",40:"Too many symbolic links",42:"No message of desired type",43:"Identifier removed",44:"Channel number out of range",45:"Level 2 not synchronized",46:"Level 3 halted",47:"Level 3 reset",48:"Link number out of range",49:"Protocol driver not attached",50:"No CSI structure available",51:"Level 2 halted",52:"Invalid exchange",53:"Invalid request descriptor",
54:"Exchange full",55:"No anode",56:"Invalid request code",57:"Invalid slot",59:"Bad font file fmt",60:"Device not a stream",61:"No data (for no delay io)",62:"Timer expired",63:"Out of streams resources",64:"Machine is not on the network",65:"Package not installed",66:"The object is remote",67:"The link has been severed",68:"Advertise error",69:"Srmount error",70:"Communication error on send",71:"Protocol error",72:"Multihop attempted",73:"Cross mount point (not really error)",74:"Trying to read unreadable message",
75:"Value too large for defined data type",76:"Given log. name not unique",77:"f.d. invalid for this operation",78:"Remote address changed",79:"Can   access a needed shared lib",80:"Accessing a corrupted shared lib",81:".lib section in a.out corrupted",82:"Attempting to link in too many libs",83:"Attempting to exec a shared library",84:"Illegal byte sequence",86:"Streams pipe error",87:"Too many users",88:"Socket operation on non-socket",89:"Destination address required",90:"Message too long",91:"Protocol wrong type for socket",
92:"Protocol not available",93:"Unknown protocol",94:"Socket type not supported",95:"Not supported",96:"Protocol family not supported",97:"Address family not supported by protocol family",98:"Address already in use",99:"Address not available",100:"Network interface is not configured",101:"Network is unreachable",102:"Connection reset by network",103:"Connection aborted",104:"Connection reset by peer",105:"No buffer space available",106:"Socket is already connected",107:"Socket is not connected",108:"Can't send after socket shutdown",
109:"Too many references",110:"Connection timed out",111:"Connection refused",112:"Host is down",113:"Host is unreachable",114:"Socket already connected",115:"Connection already in progress",116:"Stale file handle",122:"Quota exceeded",123:"No medium (in tape drive)",125:"Operation canceled",130:"Previous owner died",131:"State not recoverable"};function rb(a){e.___errno_location&&(w[e.___errno_location()>>2]=a);return a}
function sb(a,b){for(var c=0,d=a.length-1;0<=d;d--){var f=a[d];"."===f?a.splice(d,1):".."===f?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}function tb(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=sb(a.split("/").filter(function(a){return!!a}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}
function ub(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function vb(a){if("/"===a)return"/";var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}function wb(){var a=Array.prototype.slice.call(arguments,0);return tb(a.join("/"))}function F(a,b){return tb(a+"/"+b)}
function xb(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=sb(a.split("/").filter(function(a){return!!a}),!b).join("/");return(b?"/":"")+a||"."}var yb=[];function zb(a,b){yb[a]={input:[],output:[],R:b};Ab(a,Bb)}
var Bb={open:function(a){var b=yb[a.node.rdev];if(!b)throw new G(E.la);a.tty=b;a.seekable=!1},close:function(a){a.tty.R.flush(a.tty)},flush:function(a){a.tty.R.flush(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.R.La)throw new G(E.Aa);for(var f=0,g=0;g<d;g++){try{var h=a.tty.R.La(a.tty)}catch(q){throw new G(E.H);}if(void 0===h&&0===f)throw new G(E.va);if(null===h||void 0===h)break;f++;b[c+g]=h}f&&(a.node.timestamp=Date.now());return f},write:function(a,b,c,d){if(!a.tty||!a.tty.R.sa)throw new G(E.Aa);
for(var f=0;f<d;f++)try{a.tty.R.sa(a.tty,b[c+f])}catch(g){throw new G(E.H);}d&&(a.node.timestamp=Date.now());return f}},Db={La:function(a){if(!a.input.length){var b=null;if(m){var c=new Buffer(256),d=0,f=process.stdin.fd;if("win32"!=process.platform){var g=!1;try{f=fs.openSync("/dev/stdin","r"),g=!0}catch(h){}}try{d=fs.readSync(f,c,0,256,null)}catch(h){if(-1!=h.toString().indexOf("EOF"))d=0;else throw h;}g&&fs.closeSync(f);0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&
"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=Cb(b,!0)}return a.input.shift()},sa:function(a,b){null===b||10===b?(e.print(pa(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(e.print(pa(a.output,0)),a.output=[])}},Eb={sa:function(a,b){null===b||10===b?(e.printErr(pa(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&
0<a.output.length&&(e.printErr(pa(a.output,0)),a.output=[])}},H={s:null,m:function(){return H.createNode(null,"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new G(E.L);H.s||(H.s={dir:{node:{A:H.c.A,j:H.c.j,lookup:H.c.lookup,Z:H.c.Z,rename:H.c.rename,unlink:H.c.unlink,rmdir:H.c.rmdir,readdir:H.c.readdir,symlink:H.c.symlink},stream:{G:H.f.G}},file:{node:{A:H.c.A,j:H.c.j},stream:{G:H.f.G,read:H.f.read,write:H.f.write,Ba:H.f.Ba,Pa:H.f.Pa,Sa:H.f.Sa}},link:{node:{A:H.c.A,
j:H.c.j,readlink:H.c.readlink},stream:{}},Fa:{node:{A:H.c.A,j:H.c.j},stream:Fb}});c=Gb(a,b,c,d);I(c.mode)?(c.c=H.s.dir.node,c.f=H.s.dir.stream,c.b={}):32768===(c.mode&61440)?(c.c=H.s.file.node,c.f=H.s.file.stream,c.g=0,c.b=null):40960===(c.mode&61440)?(c.c=H.s.link.node,c.f=H.s.link.stream):8192===(c.mode&61440)&&(c.c=H.s.Fa.node,c.f=H.s.Fa.stream);c.timestamp=Date.now();a&&(a.b[b]=c);return c},nb:function(a){if(a.b&&a.b.subarray){for(var b=[],c=0;c<a.g;++c)b.push(a.b[c]);return b}return a.b},Jd:function(a){return a.b?
a.b.subarray?a.b.subarray(0,a.g):new Uint8Array(a.b):new Uint8Array},Ga:function(a,b){a.b&&a.b.subarray&&b>a.b.length&&(a.b=H.nb(a),a.g=a.b.length);if(!a.b||a.b.subarray){var c=a.b?a.b.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)|0),0!=c&&(b=Math.max(b,256)),c=a.b,a.b=new Uint8Array(b),0<a.g&&a.b.set(c.subarray(0,a.g),0))}else for(!a.b&&0<b&&(a.b=[]);a.b.length<b;)a.b.push(0)},wb:function(a,b){if(a.g!=b)if(0==b)a.b=null,a.g=0;else{if(!a.b||a.b.subarray){var c=a.b;a.b=new Uint8Array(new ArrayBuffer(b));
c&&a.b.set(c.subarray(0,Math.min(b,a.g)))}else if(a.b||(a.b=[]),a.b.length>b)a.b.length=b;else for(;a.b.length<b;)a.b.push(0);a.g=b}},c:{A:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;I(a.mode)?b.size=4096:32768===(a.mode&61440)?b.size=a.g:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.J=4096;b.blocks=Math.ceil(b.size/b.J);return b},
j:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&H.wb(a,b.size)},lookup:function(){throw Hb[E.C];},Z:function(a,b,c,d){return H.createNode(a,b,c,d)},rename:function(a,b,c){if(I(a.mode)){try{var d=Ib(b,c)}catch(g){}if(d)for(var f in d.b)throw new G(E.za);}delete a.parent.b[a.name];a.name=c;b.b[c]=a;a.parent=b},unlink:function(a,b){delete a.b[b]},rmdir:function(a,b){var c=Ib(a,b),d;for(d in c.b)throw new G(E.za);delete a.b[b]},readdir:function(a){var b=
[".",".."],c;for(c in a.b)a.b.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=H.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(40960!==(a.mode&61440))throw new G(E.h);return a.link}},f:{read:function(a,b,c,d,f){var g=a.node.b;if(f>=a.node.g)return 0;a=Math.min(a.node.g-f,d);assert(0<=a);if(8<a&&g.subarray)b.set(g.subarray(f,f+a),c);else for(d=0;d<a;d++)b[c+d]=g[f+d];return a},write:function(a,b,c,d,f,g){if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&
(!a.b||a.b.subarray)){if(g)return a.b=b.subarray(c,c+d),a.g=d;if(0===a.g&&0===f)return a.b=new Uint8Array(b.subarray(c,c+d)),a.g=d;if(f+d<=a.g)return a.b.set(b.subarray(c,c+d),f),d}H.Ga(a,f+d);if(a.b.subarray&&b.subarray)a.b.set(b.subarray(c,c+d),f);else for(g=0;g<d;g++)a.b[f+g]=b[c+g];a.g=Math.max(a.g,f+d);return d},G:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.g);if(0>b)throw new G(E.h);return b},Ba:function(a,b,c){H.Ga(a.node,b+c);a.node.g=Math.max(a.node.g,
b+c)},Pa:function(a,b,c,d,f,g,h){if(32768!==(a.node.mode&61440))throw new G(E.la);c=a.node.b;if(h&2||c.buffer!==b&&c.buffer!==b.buffer){if(0<f||f+d<a.node.g)c.subarray?c=c.subarray(f,f+d):c=Array.prototype.slice.call(c,f,f+d);a=!0;d=u(d);if(!d)throw new G(E.Za);b.set(c,d)}else a=!1,d=c.byteOffset;return{Md:d,Cd:a}},Sa:function(a,b,c,d,f){if(32768!==(a.node.mode&61440))throw new G(E.la);if(f&2)return 0;H.f.write(a,b,0,d,c,!1);return 0}}},J={ha:!1,zb:function(){J.ha=!!process.platform.match(/^win/);
var a=process.binding("constants");a.fs&&(a=a.fs);J.Ia={1024:a.O_APPEND,64:a.O_CREAT,128:a.O_EXCL,0:a.O_RDONLY,2:a.O_RDWR,4096:a.O_SYNC,512:a.O_TRUNC,1:a.O_WRONLY}},Da:function(a){return Buffer.v?Buffer.from(a):new Buffer(a)},m:function(a){assert(m);return J.createNode(null,"/",J.Ka(a.ra.root),0)},createNode:function(a,b,c){if(!I(c)&&32768!==(c&61440)&&40960!==(c&61440))throw new G(E.h);a=Gb(a,b,c);a.c=J.c;a.f=J.f;return a},Ka:function(a){try{var b=fs.lstatSync(a);J.ha&&(b.mode=b.mode|(b.mode&292)>>
2)}catch(c){if(!c.code)throw c;throw new G(E[c.code]);}return b.mode},o:function(a){for(var b=[];a.parent!==a;)b.push(a.name),a=a.parent;b.push(a.m.ra.root);b.reverse();return wb.apply(null,b)},mb:function(a){a&=-2656257;var b=0,c;for(c in J.Ia)a&c&&(b|=J.Ia[c],a^=c);if(a)throw new G(E.h);return b},c:{A:function(a){a=J.o(a);try{var b=fs.lstatSync(a)}catch(c){if(!c.code)throw c;throw new G(E[c.code]);}J.ha&&!b.J&&(b.J=4096);J.ha&&!b.blocks&&(b.blocks=(b.size+b.J-1)/b.J|0);return{dev:b.dev,ino:b.ino,
mode:b.mode,nlink:b.nlink,uid:b.uid,gid:b.gid,rdev:b.rdev,size:b.size,atime:b.atime,mtime:b.mtime,ctime:b.ctime,J:b.J,blocks:b.blocks}},j:function(a,b){var c=J.o(a);try{void 0!==b.mode&&(fs.chmodSync(c,b.mode),a.mode=b.mode),void 0!==b.size&&fs.truncateSync(c,b.size)}catch(d){if(!d.code)throw d;throw new G(E[d.code]);}},lookup:function(a,b){var c=F(J.o(a),b);c=J.Ka(c);return J.createNode(a,b,c)},Z:function(a,b,c,d){a=J.createNode(a,b,c,d);b=J.o(a);try{I(a.mode)?fs.mkdirSync(b,a.mode):fs.writeFileSync(b,
"",{mode:a.mode})}catch(f){if(!f.code)throw f;throw new G(E[f.code]);}return a},rename:function(a,b,c){a=J.o(a);b=F(J.o(b),c);try{fs.renameSync(a,b)}catch(d){if(!d.code)throw d;throw new G(E[d.code]);}},unlink:function(a,b){a=F(J.o(a),b);try{fs.unlinkSync(a)}catch(c){if(!c.code)throw c;throw new G(E[c.code]);}},rmdir:function(a,b){a=F(J.o(a),b);try{fs.rmdirSync(a)}catch(c){if(!c.code)throw c;throw new G(E[c.code]);}},readdir:function(a){a=J.o(a);try{return fs.readdirSync(a)}catch(b){if(!b.code)throw b;
throw new G(E[b.code]);}},symlink:function(a,b,c){a=F(J.o(a),b);try{fs.symlinkSync(c,a)}catch(d){if(!d.code)throw d;throw new G(E[d.code]);}},readlink:function(a){var b=J.o(a);try{return b=fs.readlinkSync(b),b=Jb.relative(Jb.resolve(a.m.ra.root),b)}catch(c){if(!c.code)throw c;throw new G(E[c.code]);}}},f:{open:function(a){var b=J.o(a.node);try{32768===(a.node.mode&61440)&&(a.aa=fs.openSync(b,J.mb(a.flags)))}catch(c){if(!c.code)throw c;throw new G(E[c.code]);}},close:function(a){try{32768===(a.node.mode&
61440)&&a.aa&&fs.closeSync(a.aa)}catch(b){if(!b.code)throw b;throw new G(E[b.code]);}},read:function(a,b,c,d,f){if(0===d)return 0;try{return fs.readSync(a.aa,J.Da(b.buffer),c,d,f)}catch(g){throw new G(E[g.code]);}},write:function(a,b,c,d,f){try{return fs.writeSync(a.aa,J.Da(b.buffer),c,d,f)}catch(g){throw new G(E[g.code]);}},G:function(a,b,c){if(1===c)b+=a.position;else if(2===c&&32768===(a.node.mode&61440))try{b+=fs.fstatSync(a.aa).size}catch(d){throw new G(E[d.code]);}if(0>b)throw new G(E.h);return b}}};
r+=16;r+=16;r+=16;var Kb=null,Lb={},Mb=[],Nb=1,Ob=null,Pb=!0,Qb={},G=null,Hb={};
function K(a,b){a=xb("/",a);b=b||{};if(!a)return{path:"",node:null};var c={Ja:!0,ta:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.ta)throw new G(E.ka);a=sb(a.split("/").filter(function(a){return!!a}),!1);var f=Kb;c="/";for(d=0;d<a.length;d++){var g=d===a.length-1;if(g&&b.parent)break;f=Ib(f,a[d]);c=F(c,a[d]);f.$&&(!g||g&&b.Ja)&&(f=f.$.root);if(!g||b.na)for(g=0;40960===(f.mode&61440);)if(f=Rb(c),c=xb(ub(c),f),f=K(c,{ta:b.ta}).node,40<g++)throw new G(E.ka);}return{path:c,node:f}}
function Sb(a){for(var b;;){if(a===a.parent)return a=a.m.Qa,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function Tb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%Ob.length}function Ub(a){var b=Tb(a.parent.id,a.name);a.P=Ob[b];Ob[b]=a}function Ib(a,b){var c;if(c=(c=Vb(a,"x"))?c:a.c.lookup?0:E.ia)throw new G(c,a);for(c=Ob[Tb(a.id,b)];c;c=c.P){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.c.lookup(a,b)}
function Gb(a,b,c,d){Wb||(Wb=function(a,b,c,d){a||(a=this);this.parent=a;this.m=a.m;this.$=null;this.id=Nb++;this.name=b;this.mode=c;this.c={};this.f={};this.rdev=d},Wb.prototype={},Object.defineProperties(Wb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}},sb:{get:function(){return I(this.mode)}},rb:{get:function(){return 8192===(this.mode&
61440)}}}));a=new Wb(a,b,c,d);Ub(a);return a}function I(a){return 16384===(a&61440)}var Xb={r:0,rs:1052672,"r+":2,w:577,wx:705,xw:705,"w+":578,"wx+":706,"xw+":706,a:1089,ax:1217,xa:1217,"a+":1090,"ax+":1218,"xa+":1218};function Yb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function Vb(a,b){if(Pb)return 0;if(-1===b.indexOf("r")||a.mode&292){if(-1!==b.indexOf("w")&&!(a.mode&146)||-1!==b.indexOf("x")&&!(a.mode&73))return E.ia}else return E.ia;return 0}
function Zb(a,b){try{return Ib(a,b),E.wa}catch(c){}return Vb(a,"wx")}function $b(a){var b=4096;for(a=a||0;a<=b;a++)if(!Mb[a])return a;throw new G(E.Ya);}function ac(a,b){bc||(bc=function(){},bc.prototype={},Object.defineProperties(bc.prototype,{object:{get:function(){return this.node},set:function(a){this.node=a}}}));var c=new bc,d;for(d in a)c[d]=a[d];a=c;b=$b(b);a.fd=b;return Mb[b]=a}var Fb={open:function(a){a.f=Lb[a.node.rdev].f;a.f.open&&a.f.open(a)},G:function(){throw new G(E.da);}};
function Ab(a,b){Lb[a]={f:b}}function cc(a,b){var c="/"===b,d=!b;if(c&&Kb)throw new G(E.ja);if(!c&&!d){var f=K(b,{Ja:!1});b=f.path;f=f.node;if(f.$)throw new G(E.ja);if(!I(f.mode))throw new G(E.ya);}b={type:a,ra:{},Qa:b,tb:[]};a=a.m(b);a.m=b;b.root=a;c?Kb=a:f&&(f.$=b,f.m&&f.m.tb.push(b))}function dc(a,b,c){var d=K(a,{parent:!0}).node;a=vb(a);if(!a||"."===a||".."===a)throw new G(E.h);var f=Zb(d,a);if(f)throw new G(f);if(!d.c.Z)throw new G(E.L);return d.c.Z(d,a,b,c)}
function L(a,b){return dc(a,(void 0!==b?b:511)&1023|16384,0)}function ec(a,b,c){"undefined"===typeof c&&(c=b,b=438);return dc(a,b|8192,c)}function fc(a,b){if(!xb(a))throw new G(E.C);var c=K(b,{parent:!0}).node;if(!c)throw new G(E.C);b=vb(b);var d=Zb(c,b);if(d)throw new G(d);if(!c.c.symlink)throw new G(E.L);return c.c.symlink(c,b,a)}
function hc(a){var b=K(a,{parent:!0}).node,c=vb(a),d=Ib(b,c);a:{try{var f=Ib(b,c)}catch(h){f=h.D;break a}var g=Vb(b,"wx");f=g?g:I(f.mode)?E.U:0}if(f)throw new G(f);if(!b.c.unlink)throw new G(E.L);if(d.$)throw new G(E.ja);try{Qb.willDeletePath&&Qb.willDeletePath(a)}catch(h){console.log("FS.trackingDelegate['willDeletePath']('"+a+"') threw an exception: "+h.message)}b.c.unlink(b,c);b=Tb(d.parent.id,d.name);if(Ob[b]===d)Ob[b]=d.P;else for(b=Ob[b];b;){if(b.P===d){b.P=d.P;break}b=b.P}try{if(Qb.onDeletePath)Qb.onDeletePath(a)}catch(h){console.log("FS.trackingDelegate['onDeletePath']('"+
a+"') threw an exception: "+h.message)}}function Rb(a){a=K(a).node;if(!a)throw new G(E.C);if(!a.c.readlink)throw new G(E.h);return xb(Sb(a.parent),a.c.readlink(a))}function ic(a,b){var c;"string"===typeof a?c=K(a,{na:!0}).node:c=a;if(!c.c.j)throw new G(E.L);c.c.j(c,{mode:b&4095|c.mode&-4096,timestamp:Date.now()})}
function jc(a,b,c,d){if(""===a)throw new G(E.C);if("string"===typeof b){var f=Xb[b];if("undefined"===typeof f)throw Error("Unknown file open mode: "+b);b=f}c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var g=a;else{a=tb(a);try{g=K(a,{na:!(b&131072)}).node}catch(q){}}f=!1;if(b&64)if(g){if(b&128)throw new G(E.wa);}else g=dc(a,c,0),f=!0;if(!g)throw new G(E.C);8192===(g.mode&61440)&&(b&=-513);if(b&65536&&!I(g.mode))throw new G(E.ya);if(!f&&(c=g?40960===(g.mode&61440)?E.ka:
I(g.mode)&&("r"!==Yb(b)||b&512)?E.U:Vb(g,Yb(b)):E.C))throw new G(c);if(b&512){c=g;var h;"string"===typeof c?h=K(c,{na:!0}).node:h=c;if(!h.c.j)throw new G(E.L);if(I(h.mode))throw new G(E.U);if(32768!==(h.mode&61440))throw new G(E.h);if(c=Vb(h,"w"))throw new G(c);h.c.j(h,{size:0,timestamp:Date.now()})}b&=-641;d=ac({node:g,path:Sb(g),flags:b,seekable:!0,position:0,f:g.f,Ab:[],error:!1},d);d.f.open&&d.f.open(d);!e.logReadFiles||b&1||(kc||(kc={}),a in kc||(kc[a]=1,e.printErr("read file: "+a)));try{Qb.onOpenFile&&
(g=0,1!==(b&2097155)&&(g|=1),0!==(b&2097155)&&(g|=2),Qb.onOpenFile(a,g))}catch(q){console.log("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+q.message)}return d}function lc(a){a.oa&&(a.oa=null);try{a.f.close&&a.f.close(a)}catch(b){throw b;}finally{Mb[a.fd]=null}}function mc(a,b,c){if(!a.seekable||!a.f.G)throw new G(E.da);a.position=a.f.G(a,b,c);a.Ab=[]}
function nc(a,b,c,d,f,g){if(0>d||0>f)throw new G(E.h);if(0===(a.flags&2097155))throw new G(E.ba);if(I(a.node.mode))throw new G(E.U);if(!a.f.write)throw new G(E.h);a.flags&1024&&mc(a,0,2);var h="undefined"!==typeof f;if(!h)f=a.position;else if(!a.seekable)throw new G(E.da);b=a.f.write(a,b,c,d,f,g);h||(a.position+=b);try{if(a.path&&Qb.onWriteToFile)Qb.onWriteToFile(a.path)}catch(q){console.log("FS.trackingDelegate['onWriteToFile']('"+path+"') threw an exception: "+q.message)}return b}
function oc(){G||(G=function(a,b){this.node=b;this.yb=function(a){this.D=a;for(var b in E)if(E[b]===a){this.code=b;break}};this.yb(a);this.message=qb[a];this.stack&&Object.defineProperty(this,"stack",{value:Error().stack,writable:!0})},G.prototype=Error(),G.prototype.constructor=G,[E.C].forEach(function(a){Hb[a]=new G(a);Hb[a].stack="<generic error, no stack>"}))}var pc;function qc(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}
function rc(a,b,c,d){a=F("string"===typeof a?a:Sb(a),b);return L(a,qc(c,d))}function sc(a,b){a="string"===typeof a?a:Sb(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=F(a,c);try{L(d)}catch(f){}a=d}}return d}function tc(a,b,c,d){a=F("string"===typeof a?a:Sb(a),b);c=qc(c,d);return dc(a,(void 0!==c?c:438)&4095|32768,0)}
function uc(a,b,c,d,f,g){a=b?F("string"===typeof a?a:Sb(a),b):a;d=qc(d,f);f=dc(a,(void 0!==d?d:438)&4095|32768,0);if(c){if("string"===typeof c){a=Array(c.length);b=0;for(var h=c.length;b<h;++b)a[b]=c.charCodeAt(b);c=a}ic(f,d|146);a=jc(f,"w");nc(a,c,0,c.length,0,g);lc(a);ic(f,d)}return f}
function M(a,b,c,d){a=F("string"===typeof a?a:Sb(a),b);b=qc(!!c,!!d);M.Oa||(M.Oa=64);var f=M.Oa++<<8|0;Ab(f,{open:function(a){a.seekable=!1},close:function(){d&&d.buffer&&d.buffer.length&&d(10)},read:function(a,b,d,f){for(var g=0,h=0;h<f;h++){try{var q=c()}catch(Y){throw new G(E.H);}if(void 0===q&&0===g)throw new G(E.va);if(null===q||void 0===q)break;g++;b[d+h]=q}g&&(a.node.timestamp=Date.now());return g},write:function(a,b,c,f){for(var g=0;g<f;g++)try{d(b[c+g])}catch(v){throw new G(E.H);}f&&(a.node.timestamp=
Date.now());return g}});return ec(a,b,f)}function vc(a,b,c){a=F("string"===typeof a?a:Sb(a),b);return fc(c,a)}
function wc(a){if(a.rb||a.sb||a.link||a.b)return!0;var b=!0;if("undefined"!==typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");if(e.read)try{a.b=Cb(e.read(a.url),!0),a.g=a.b.length}catch(c){b=!1}else throw Error("Cannot load without read() or XMLHttpRequest.");b||rb(E.H);return b}
function xc(a,b,c,d,f){function g(){this.pa=!1;this.fa=[]}g.prototype.get=function(a){if(!(a>this.length-1||0>a)){var b=a%this.chunkSize;return this.Ma(a/this.chunkSize|0)[b]}};g.prototype.xb=function(a){this.Ma=a};g.prototype.Ea=function(){var a=new XMLHttpRequest;a.open("HEAD",c,!1);a.send(null);if(!(200<=a.status&&300>a.status||304===a.status))throw Error("Couldn't load "+c+". Status: "+a.status);var b=Number(a.getResponseHeader("Content-length")),d,f=(d=a.getResponseHeader("Accept-Ranges"))&&
"bytes"===d;a=(d=a.getResponseHeader("Content-Encoding"))&&"gzip"===d;var g=1048576;f||(g=b);var h=this;h.xb(function(a){var d=a*g,f=(a+1)*g-1;f=Math.min(f,b-1);if("undefined"===typeof h.fa[a]){var q=h.fa;if(d>f)throw Error("invalid range ("+d+", "+f+") or no bytes requested!");if(f>b-1)throw Error("only "+b+" bytes available! programmer error!");var n=new XMLHttpRequest;n.open("GET",c,!1);b!==g&&n.setRequestHeader("Range","bytes="+d+"-"+f);"undefined"!=typeof Uint8Array&&(n.responseType="arraybuffer");
n.overrideMimeType&&n.overrideMimeType("text/plain; charset=x-user-defined");n.send(null);if(!(200<=n.status&&300>n.status||304===n.status))throw Error("Couldn't load "+c+". Status: "+n.status);d=void 0!==n.response?new Uint8Array(n.response||[]):Cb(n.responseText||"",!0);q[a]=d}if("undefined"===typeof h.fa[a])throw Error("doXHR failed!");return h.fa[a]});if(a||!b)g=b=1,g=b=this.Ma(0).length,console.log("LazyFiles on gzip forces download of the whole file when length is accessed");this.ab=b;this.$a=
g;this.pa=!0};if("undefined"!==typeof XMLHttpRequest){if(!l)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";var h=new g;Object.defineProperties(h,{length:{get:function(){this.pa||this.Ea();return this.ab}},chunkSize:{get:function(){this.pa||this.Ea();return this.$a}}});var q=void 0}else q=c,h=void 0;var n=tc(a,b,d,f);h?n.b=h:q&&(n.b=null,n.url=q);Object.defineProperties(n,{g:{get:function(){return this.b.length}}});var p={};
Object.keys(n.f).forEach(function(a){var b=n.f[a];p[a]=function(){if(!wc(n))throw new G(E.H);return b.apply(null,arguments)}});p.read=function(a,b,c,d,f){if(!wc(n))throw new G(E.H);a=a.node.b;if(f>=a.length)return 0;d=Math.min(a.length-f,d);assert(0<=d);if(a.slice)for(var g=0;g<d;g++)b[c+g]=a[f+g];else for(g=0;g<d;g++)b[c+g]=a.get(f+g);return d};n.f=p;return n}
function yc(a,b,c,d,f,g,h,q,n,p){function v(c){function x(c){p&&p();q||uc(a,b,c,d,f,n);g&&g();Va()}var v=!1;e.preloadPlugins.forEach(function(a){!v&&a.canHandle(y)&&(a.handle(c,y,x,function(){h&&h();Va()}),v=!0)});v||x(c)}zc();var y=b?xb(F(a,b)):a;Ua();"string"==typeof c?Ac(c,function(a){v(a)},h):v(c)}var FS={},Wb,bc,kc,N=0;function O(){N+=4;return w[N-4>>2]}function Bc(){var a=Mb[O()];if(!a)throw new G(E.ba);return a}function Cc(){t()}var P=0,Dc=0,Q=0,Ec=0,Fc=0,Gc=0,Hc=null,Ic=null,Jc=null,Kc=!1;
function Lc(){Kc||(Na.push(function(){for(var a=Mc.length-1;0<=a;--a)Nc(a)}),Kc=!0)}function R(a){return a?("number"==typeof a&&(a=A(a)),"#window"==a?window:"#document"==a?document:"#screen"==a?window.screen:"#canvas"==a?e.canvas:"string"==typeof a?document.getElementById(a):a):window}var S=[];
function Oc(a){var b=Pc;function c(a,b){if(a.length!=b.length)return!1;for(var c in a)if(a[c]!=b[c])return!1;return!0}for(var d in S){var f=S[d];if(f.ua==b&&c(f.Ca,a))return}S.push({ua:b,Ua:1,Ca:a});S.sort(function(a,b){return a.Ua<b.Ua})}function Qc(){if(Rc&&Sc.I)for(var a=0;a<S.length;++a){var b=S[a];S.splice(a,1);--a;b.ua.apply(this,b.Ca)}}var Rc=0,Sc=null,Mc=[];function Tc(){return-1!==navigator.userAgent.indexOf("MSIE")||0<navigator.appVersion.indexOf("Trident/")}
function Nc(a){var b=Mc[a];b.target.removeEventListener(b.F,b.kb,b.T);Mc.splice(a,1)}function Uc(a){function b(b){++Rc;Sc=a;Qc();a.W(b);Qc();--Rc}if(a.V)a.kb=b,a.target.addEventListener(a.F,b,a.T),Mc.push(a),Lc();else for(var c=0;c<Mc.length;++c)Mc[c].target==a.target&&Mc[c].F==a.F&&Nc(c--)}
function Vc(a,b,c,d,f,g){P||(P=u(164));a={target:R(a),I:Tc()?!1:!0,F:g,V:d,W:function(a){a=a||window.event;B(a.key?a.key:"",z,P+0,32);B(a.code?a.code:"",z,P+32,32);w[P+64>>2]=a.location;w[P+68>>2]=a.ctrlKey;w[P+72>>2]=a.shiftKey;w[P+76>>2]=a.altKey;w[P+80>>2]=a.metaKey;w[P+84>>2]=a.repeat;B(a.locale?a.locale:"",z,P+88,32);B(a.char?a.char:"",z,P+120,32);w[P+152>>2]=a.charCode;w[P+156>>2]=a.keyCode;w[P+160>>2]=a.which;e.dynCall_iiii(d,f,P,b)&&a.preventDefault()},T:c};Uc(a)}
function Wc(a,b,c){D[a>>3]=window.performance&&window.performance.now?window.performance.now():Date.now();w[a+8>>2]=b.screenX;w[a+12>>2]=b.screenY;w[a+16>>2]=b.clientX;w[a+20>>2]=b.clientY;w[a+24>>2]=b.ctrlKey;w[a+28>>2]=b.shiftKey;w[a+32>>2]=b.altKey;w[a+36>>2]=b.metaKey;ua[a+40>>1]=b.button;ua[a+42>>1]=b.buttons;w[a+44>>2]=b.movementX||b.mozMovementX||b.webkitMovementX||b.screenX-Ic;w[a+48>>2]=b.movementY||b.mozMovementY||b.webkitMovementY||b.screenY-Jc;if(e.canvas){var d=e.canvas.getBoundingClientRect();
w[a+60>>2]=b.clientX-d.left;w[a+64>>2]=b.clientY-d.top}else w[a+60>>2]=0,w[a+64>>2]=0;c?(d=c.getBoundingClientRect?c.getBoundingClientRect():{left:0,top:0},w[a+52>>2]=b.clientX-d.left,w[a+56>>2]=b.clientY-d.top):(w[a+52>>2]=0,w[a+56>>2]=0);"wheel"!==b.type&&"mousewheel"!==b.type&&(Ic=b.screenX,Jc=b.screenY)}
function Xc(a,b,c,d,f,g){Dc||(Dc=u(72));a=R(a);c={target:a,I:"mousemove"!=g&&"mouseenter"!=g&&"mouseleave"!=g,F:g,V:d,W:function(c){c=c||window.event;Wc(Dc,c,a);e.dynCall_iiii(d,f,Dc,b)&&c.preventDefault()},T:c};Tc()&&"mousedown"==g&&(c.I=!1);Uc(c)}
function Yc(a,b,c,d,f){function g(c){c=c||window.event;Wc(Q,c,a);D[Q+72>>3]=c.wheelDeltaX||0;D[Q+80>>3]=-(c.wheelDeltaY?c.wheelDeltaY:c.wheelDelta);D[Q+88>>3]=0;w[Q+96>>2]=0;e.dynCall_iiii(d,9,Q,b)&&c.preventDefault()}function h(c){c=c||window.event;Wc(Q,c,a);D[Q+72>>3]=c.deltaX;D[Q+80>>3]=c.deltaY;D[Q+88>>3]=c.deltaZ;w[Q+96>>2]=c.deltaMode;e.dynCall_iiii(d,9,Q,b)&&c.preventDefault()}Q||(Q=u(104));a=R(a);Uc({target:a,I:!0,F:f,V:d,W:"wheel"==f?h:g,T:c})}
function Zc(){return document.fullscreenEnabled||document.mozFullScreenEnabled||document.webkitFullscreenEnabled||document.msFullscreenEnabled}
function $c(a){var b=document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.msFullscreenElement,c=!!b;w[a>>2]=c;w[a+4>>2]=Zc();var d=c?b:Hc,f=d&&d.id?d.id:"";B(d?d==window?"#window":d==window.screen?"#screen":d&&d.nodeName?d.nodeName:"":"",z,a+8,128);B(f,z,a+136,128);w[a+264>>2]=d?d.clientWidth:0;w[a+268>>2]=d?d.clientHeight:0;w[a+272>>2]=screen.width;w[a+276>>2]=screen.height;c&&(Hc=b)}
function ad(a,b,c,d,f){Ec||(Ec=u(280));a?a=R(a):a=document;Uc({target:a,I:!1,F:f,V:d,W:function(a){a=a||window.event;$c(Ec);e.dynCall_iiii(d,19,Ec,b)&&a.preventDefault()},T:c})}
function bd(a,b){var c=__registerRestoreOldStyle(a),d=b.Wa?window.innerWidth:screen.width,f=b.Wa?window.innerHeight:screen.height,g=a.getBoundingClientRect(),h=g.right-g.left;g=g.bottom-g.top;var q=a.width,n=a.height;3==b.S?(__setLetterbox(a,(f-g)/2,(d-h)/2),d=h,f=g):2==b.S&&(d*n<q*f?(h=n*d/q,__setLetterbox(a,(f-h)/2,0),f=h):(h=q*f/n,__setLetterbox(a,0,(d-h)/2),d=h));a.style.backgroundColor||(a.style.backgroundColor="black");document.body.style.backgroundColor||(document.body.style.backgroundColor=
"black");a.style.width=d+"px";a.style.height=f+"px";1==b.Ha&&(a.style.Na="pixelated");h=2==b.N?window.devicePixelRatio:1;0!=b.N&&(a.width=d*h,a.height=f*h,a.u&&a.u.GLctx.viewport(0,0,a.width,a.height));return c}
function Pc(a,b){0==b.S&&0==b.N||bd(a,b);if(a.requestFullscreen)a.requestFullscreen();else if(a.msRequestFullscreen)a.msRequestFullscreen();else if(a.mozRequestFullScreen)a.mozRequestFullScreen();else if(a.Ra)a.Ra();else if(a.webkitRequestFullscreen)a.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT);else return"undefined"===typeof Zc()?-1:-3;b.l&&e.dynCall_iiii(b.l,37,0,b.M);return 0}
function cd(a,b,c,d,f,g){Fc||(Fc=u(1684));a=R(a);Uc({target:a,I:"touchstart"==g||"touchend"==g,F:g,V:d,W:function(c){c=c||window.event;for(var g={},h=0;h<c.touches.length;++h){var p=c.touches[h];g[p.identifier]=p}for(h=0;h<c.changedTouches.length;++h)p=c.changedTouches[h],g[p.identifier]=p,p.fb=!0;for(h=0;h<c.targetTouches.length;++h)p=c.targetTouches[h],g[p.identifier].ub=!0;p=Fc;w[p+4>>2]=c.ctrlKey;w[p+8>>2]=c.shiftKey;w[p+12>>2]=c.altKey;w[p+16>>2]=c.metaKey;p+=20;var v=e.canvas?e.canvas.getBoundingClientRect():
void 0,y=a.getBoundingClientRect?a.getBoundingClientRect():{left:0,top:0},Y=0;for(h in g){var x=g[h];w[p>>2]=x.identifier;w[p+4>>2]=x.screenX;w[p+8>>2]=x.screenY;w[p+12>>2]=x.clientX;w[p+16>>2]=x.clientY;w[p+20>>2]=x.pageX;w[p+24>>2]=x.pageY;w[p+28>>2]=x.fb;w[p+32>>2]=x.ub;v?(w[p+44>>2]=x.clientX-v.left,w[p+48>>2]=x.clientY-v.top):(w[p+44>>2]=0,w[p+48>>2]=0);w[p+36>>2]=x.clientX-y.left;w[p+40>>2]=x.clientY-y.top;p+=52;if(32<=++Y)break}w[Fc>>2]=Y;e.dynCall_iiii(d,f,Fc,b)&&c.preventDefault()},T:c})}
function __setLetterbox(a,b,c){Tc()?(a.style.marginLeft=a.style.marginRight=c+"px",a.style.marginTop=a.style.marginBottom=b+"px"):(a.style.paddingLeft=a.style.paddingRight=c+"px",a.style.paddingTop=a.style.paddingBottom=b+"px")}function dd(a){for(var b=a.parentNode,c=[];a!=document.body;){for(var d=b.children,f=0;f<d.length;++f)d[f]!=a&&(c.push({node:d[f],jb:d[f].style.display}),d[f].style.display="none");a=b;b=b.parentNode}return c}var ed=null;
function __registerRestoreOldStyle(a){function b(){document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.msFullscreenElement||(document.removeEventListener("fullscreenchange",b),document.removeEventListener("mozfullscreenchange",b),document.removeEventListener("webkitfullscreenchange",b),document.removeEventListener("MSFullscreenChange",b),a.width=c,a.height=d,a.style.width=f,a.style.height=g,a.style.backgroundColor=h,q||(document.body.style.backgroundColor=
"white"),document.body.style.backgroundColor=q,a.style.paddingLeft=n,a.style.paddingRight=p,a.style.paddingTop=v,a.style.paddingBottom=y,a.style.marginLeft=Y,a.style.marginRight=x,a.style.marginTop=va,a.style.marginBottom=Ea,document.body.style.margin=ge,document.documentElement.style.overflow=he,document.body.scroll=ie,a.style.Na=je,a.u&&a.u.GLctx.viewport(0,0,c,d),T.l&&e.dynCall_iiii(T.l,37,0,T.M))}var c=a.width,d=a.height,f=a.style.width,g=a.style.height,h=a.style.backgroundColor,q=document.body.style.backgroundColor,
n=a.style.paddingLeft,p=a.style.paddingRight,v=a.style.paddingTop,y=a.style.paddingBottom,Y=a.style.marginLeft,x=a.style.marginRight,va=a.style.marginTop,Ea=a.style.marginBottom,ge=document.body.style.margin,he=document.documentElement.style.overflow,ie=document.body.scroll,je=a.style.Na;document.addEventListener("fullscreenchange",b);document.addEventListener("mozfullscreenchange",b);document.addEventListener("webkitfullscreenchange",b);document.addEventListener("MSFullscreenChange",b);return b}
var T={};
function fd(){var a=2==T.N,b=0!=T.N,c=3==T.S,d=a?Math.round(window.innerHeight*window.devicePixelRatio):window.innerHeight,f=a?Math.round(window.innerWidth*window.devicePixelRatio):window.innerWidth,g=d,h=T.target,q=h.width,n=h.height;if(2==T.S){f*n<q*g?g=f*n/q|0:f*n>q*g&&(f=g*q/n|0);var p=(d-g)/2|0}b&&(h.width=f,h.height=g,h.u&&h.u.GLctx.viewport(0,0,h.width,h.height));a&&(p/=window.devicePixelRatio,f/=window.devicePixelRatio,g/=window.devicePixelRatio,f=Math.round(1E4*f)/1E4,g=Math.round(1E4*g)/
1E4,p=Math.round(1E4*p)/1E4);c?(a=(window.innerWidth-parseInt(h.style.width))/2,__setLetterbox(h,(window.innerHeight-parseInt(h.style.height))/2,a)):(h.style.width=f+"px",h.style.height=g+"px",a=(window.innerWidth-f)/2,__setLetterbox(h,p,a));!c&&T.l&&e.dynCall_iiii(T.l,37,0,T.M)}function gd(a,b){e.setThrew(a,b||1);throw"longjmp";}
function hd(a,b){if("undefined"===typeof Zc())return-1;if(!Zc())return-3;a||(a="#canvas");a=R(a);return a?a.requestFullscreen||a.msRequestFullscreen||a.mozRequestFullScreen||a.Ra||a.webkitRequestFullscreen?Rc&&Sc.I?Pc(a,b):b.ib?(Oc([a,b]),1):-2:-3:-4}var id=null,jd="",kd=0,ld=null,md=0,nd=0,od=0,pd=0,qd=[],rd={},sd,td,ud,vd=!1,wd=!1,xd=[];
function zc(){function a(){wd=document.pointerLockElement===e.canvas||document.mozPointerLockElement===e.canvas||document.webkitPointerLockElement===e.canvas||document.msPointerLockElement===e.canvas}e.preloadPlugins||(e.preloadPlugins=[]);if(!yd){yd=!0;try{zd=!0}catch(c){zd=!1,console.log("warning: no blob constructor, cannot create blobs with mimetypes")}Ad="undefined"!=typeof MozBlobBuilder?MozBlobBuilder:"undefined"!=typeof WebKitBlobBuilder?WebKitBlobBuilder:zd?null:console.log("warning: no BlobBuilder");
Bd="undefined"!=typeof window?window.URL?window.URL:window.webkitURL:void 0;e.Ta||"undefined"!==typeof Bd||(console.log("warning: Browser does not support creating object URLs. Built-in browser image decoding will not be available."),e.Ta=!0);e.preloadPlugins.push({canHandle:function(a){return!e.Ta&&/\.(jpg|jpeg|png|bmp)$/i.test(a)},handle:function(a,b,f,g){var c=null;if(zd)try{c=new Blob([a],{type:Cd(b)}),c.size!==a.length&&(c=new Blob([(new Uint8Array(a)).buffer],{type:Cd(b)}))}catch(p){ka("Blob constructor present but fails: "+
p+"; falling back to blob builder")}c||(c=new Ad,c.append((new Uint8Array(a)).buffer),c=c.getBlob());var d=Bd.createObjectURL(c),n=new Image;n.onload=function(){assert(n.complete,"Image "+b+" could not be decoded");var c=document.createElement("canvas");c.width=n.width;c.height=n.height;c.getContext("2d").drawImage(n,0,0);e.preloadedImages[b]=c;Bd.revokeObjectURL(d);f&&f(a)};n.onerror=function(){console.log("Image "+d+" could not be decoded");g&&g()};n.src=d}});e.preloadPlugins.push({canHandle:function(a){return!e.Ld&&
a.substr(-4)in{".ogg":1,".wav":1,".mp3":1}},handle:function(a,b,f,g){function c(c){n||(n=!0,e.preloadedAudios[b]=c,f&&f(a))}function d(){n||(n=!0,e.preloadedAudios[b]=new Audio,g&&g())}var n=!1;if(zd){try{var p=new Blob([a],{type:Cd(b)})}catch(y){return d()}p=Bd.createObjectURL(p);var v=new Audio;v.addEventListener("canplaythrough",function(){c(v)},!1);v.onerror=function(){if(!n){console.log("warning: browser could not fully decode audio "+b+", trying slower base64 approach");for(var d="",f=0,g=0,
h=0;h<a.length;h++)for(f=f<<8|a[h],g+=8;6<=g;){var p=f>>g-6&63;g-=6;d+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[p]}2==g?(d+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(f&3)<<4],d+="=="):4==g&&(d+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(f&15)<<2],d+="=");v.src="data:audio/x-"+b.substr(-3)+";base64,"+d;c(v)}};v.src=p;Dd(function(){c(v)})}else return d()}});var b=e.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||
b.webkitRequestPointerLock||b.msRequestPointerLock||function(){},b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||function(){},b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),e.elementPointerLock&&
b.addEventListener("click",function(a){!wd&&e.canvas.requestPointerLock&&(e.canvas.requestPointerLock(),a.preventDefault())},!1))}}
function Ed(a,b,c,d){if(b&&e.ga&&a==e.canvas)return e.ga;if(b){var f={antialias:!1,alpha:!1};if(d)for(var g in d)f[g]=d[g];if(f=Fd(a,f))var h=Gd[f].GLctx}else h=a.getContext("2d");if(!h)return null;c&&(b||assert("undefined"===typeof GLctx,"cannot set in module if GLctx is used, but we are a non-GL context that would replace it"),e.ga=h,b&&Hd(f),e.Od=b,xd.forEach(function(a){a()}),zc());return h}var Id=!1,Jd=void 0,Kd=void 0;
function Ld(a,b,c){function d(){vd=!1;var a=f.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a?(f.exitFullscreen=document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||function(){},f.exitFullscreen=f.exitFullscreen.bind(document),Jd&&f.requestPointerLock(),vd=!0,Kd&&("undefined"!=typeof SDL&&
(w[SDL.screen>>2]=xa[SDL.screen>>2]|8388608),Md())):(a.parentNode.insertBefore(f,a),a.parentNode.removeChild(a),Kd&&("undefined"!=typeof SDL&&(w[SDL.screen>>2]=xa[SDL.screen>>2]&-8388609),Md()));if(e.onFullScreen)e.onFullScreen(vd);if(e.onFullscreen)e.onFullscreen(vd);Nd(f)}Jd=a;Kd=b;Od=c;"undefined"===typeof Jd&&(Jd=!0);"undefined"===typeof Kd&&(Kd=!1);"undefined"===typeof Od&&(Od=null);var f=e.canvas;Id||(Id=!0,document.addEventListener("fullscreenchange",d,!1),document.addEventListener("mozfullscreenchange",
d,!1),document.addEventListener("webkitfullscreenchange",d,!1),document.addEventListener("MSFullscreenChange",d,!1));var g=document.createElement("div");f.parentNode.insertBefore(g,f);g.appendChild(f);g.requestFullscreen=g.requestFullscreen||g.mozRequestFullScreen||g.msRequestFullscreen||(g.webkitRequestFullscreen?function(){g.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT)}:null)||(g.webkitRequestFullScreen?function(){g.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT)}:null);c?g.requestFullscreen({Qd:c}):
g.requestFullscreen()}function Pd(a,b,c){e.printErr("Browser.requestFullScreen() is deprecated. Please call Browser.requestFullscreen instead.");Pd=function(a,b,c){return Ld(a,b,c)};return Ld(a,b,c)}var Qd=0;function Rd(a){var b=Date.now();if(0===Qd)Qd=b+1E3/60;else for(;b+2>=Qd;)Qd+=1E3/60;setTimeout(a,Math.max(Qd-b,0))}
function Sd(a){"undefined"===typeof window?Rd(a):(window.requestAnimationFrame||(window.requestAnimationFrame=window.requestAnimationFrame||window.mozRequestAnimationFrame||window.webkitRequestAnimationFrame||window.msRequestAnimationFrame||window.oRequestAnimationFrame||Rd),window.requestAnimationFrame(a))}function Dd(a){e.noExitRuntime=!0;setTimeout(function(){ma||a()},1E4)}
function Cd(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.substr(a.lastIndexOf(".")+1)]}function Ac(a,b,c){var d="al "+a;e.readAsync(a,function(c){assert(c,'Loading data file "'+a+'" failed (no arrayBuffer).');b(new Uint8Array(c));d&&Va()},function(){if(c)c();else throw'Loading data file "'+a+'" failed.';});d&&Ua()}var Td=[];function Md(){var a=e.canvas;Td.forEach(function(b){b(a.width,a.height)})}
function Nd(a,b,c){b&&c?(a.Bb=b,a.ob=c):(b=a.Bb,c=a.ob);var d=b,f=c;e.forcedAspectRatio&&0<e.forcedAspectRatio&&(d/f<e.forcedAspectRatio?d=Math.round(f*e.forcedAspectRatio):f=Math.round(d/e.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var g=Math.min(screen.width/d,screen.height/f);d=Math.round(d*g);f=Math.round(f*
g)}Kd?(a.width!=d&&(a.width=d),a.height!=f&&(a.height=f),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||f!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",f+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}var yd,zd,Ad,Bd,Od;
function Ud(a,b){nd=a;od=b;if(ld)if(0==a)id=function(){var a=Math.max(0,td+b-Cc())|0;setTimeout(ud,a)},jd="timeout";else if(1==a)id=function(){Sd(ud)},jd="rAF";else if(2==a){if("undefined"===typeof setImmediate){var c=[];addEventListener("message",function(a){if("setimmediate"===a.data||"setimmediate"===a.data.target)a.stopPropagation(),c.shift()()},!0);setImmediate=function(a){c.push(a);l?(void 0===e.setImmediates&&(e.setImmediates=[]),e.setImmediates.push(a),postMessage({target:"setimmediate"})):
postMessage("setimmediate","*")}}id=function(){setImmediate(ud)};jd="immediate"}}
function Vd(a,b,c,d,f){e.noExitRuntime=!0;assert(!ld,"emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.");ld=a;md=d;var g="undefined"!==typeof d?function(){e.dynCall_vi(a,d)}:function(){e.dynCall_v(a)};var h=kd;ud=function(){if(!ma)if(0<qd.length){var a=Date.now(),b=qd.shift();b.i(b.ea);if(sd){var c=sd,d=0==c%1?c-1:Math.floor(c);sd=b.Dd?d:(8*c+(d+.5))/9}console.log('main loop blocker "'+
b.name+'" took '+(Date.now()-a)+" ms");e.setStatus&&(a=e.statusMessage||"Please wait...",b=sd,c=rd.Gd,b?b<c?e.setStatus(a+" ("+(c-b)+"/"+c+")"):e.setStatus(a):e.setStatus(""));h<kd||setTimeout(ud,0)}else if(!(h<kd))if(pd=pd+1|0,1==nd&&1<od&&0!=pd%od)id();else{0==nd&&(td=Cc());"timeout"===jd&&e.ga&&(e.printErr("Looks like you are rendering without using requestAnimationFrame for the main loop. You should use 0 for the frame rate in emscripten_set_main_loop in order to use requestAnimationFrame, as that can greatly improve your frame rates!"),
jd="");a:if(!(ma||e.preMainLoop&&!1===e.preMainLoop())){try{g()}catch(y){if(y instanceof fa)break a;y&&"object"===typeof y&&y.stack&&e.printErr("exception thrown: "+[y,y.stack]);throw y;}e.postMainLoop&&e.postMainLoop()}h<kd||("object"===typeof SDL&&SDL.audio&&SDL.audio.vb&&SDL.audio.vb(),id())}};f||(b&&0<b?Ud(0,1E3/b):Ud(1,1),id());if(c)throw"SimulateInfiniteLoop";}var Wd=1,Xd=0,Yd=[],U=[],Zd=[],$d=[],ae=[],V=[],W=[],Gd=[],X=null,be={},ce={},de={},ee=[],fe=4;function Z(a){Xd||(Xd=a)}
function ke(a){for(var b=Wd++,c=a.length;c<b;c++)a[c]=null;return b}var le=null,me=[0];
function Fd(a,b){function c(a){d=a.statusMessage||d}"undefined"===typeof b.majorVersion&&"undefined"===typeof b.minorVersion&&(b.majorVersion="undefined"!==typeof WebGL2RenderingContext?2:1,b.minorVersion=0);var d="?";try{a.addEventListener("webglcontextcreationerror",c,!1);try{if(1==b.majorVersion&&0==b.minorVersion)var f=a.getContext("webgl",b)||a.getContext("experimental-webgl",b);else if(2==b.majorVersion&&0==b.minorVersion)f=a.getContext("webgl2",b);else throw"Unsupported WebGL context version "+
majorVersion+"."+minorVersion+"!";}finally{a.removeEventListener("webglcontextcreationerror",c,!1)}if(!f)throw":(";}catch(g){return e.print("Could not create canvas: "+[d,g,JSON.stringify(b)]),0}return f?ne(f,b):0}
function ne(a,b){function c(){var a=navigator.userAgent.match(/Chrom(e|ium)\/([0-9]+)\./);return a?parseInt(a[2],10):!1}var d=ke(Gd),f={handle:d,attributes:b,version:b.majorVersion,GLctx:a};f.B=2<=f.version&&(!1===c()||58<=c());a.canvas&&(a.canvas.u=f);Gd[d]=f;("undefined"===typeof b.enableExtensionsByDefault||b.enableExtensionsByDefault)&&oe(f);return d}function Hd(a){a=Gd[a];if(!a)return!1;GLctx=e.ga=a.GLctx;X=a;return!0}
function oe(a){a||(a=X);if(!a.pb){a.pb=!0;var b=a.GLctx;a.Kd=b.getParameter(b.MAX_VERTEX_ATTRIBS);if(2>a.version){var c=b.getExtension("ANGLE_instanced_arrays");c&&(b.vertexAttribDivisor=function(a,b){c.vertexAttribDivisorANGLE(a,b)},b.drawArraysInstanced=function(a,b,d,f){c.drawArraysInstancedANGLE(a,b,d,f)},b.drawElementsInstanced=function(a,b,d,f,g){c.drawElementsInstancedANGLE(a,b,d,f,g)});var d=b.getExtension("OES_vertex_array_object");d&&(b.createVertexArray=function(){return d.createVertexArrayOES()},
b.deleteVertexArray=function(a){d.deleteVertexArrayOES(a)},b.bindVertexArray=function(a){d.bindVertexArrayOES(a)},b.isVertexArray=function(a){return d.isVertexArrayOES(a)});var f=b.getExtension("WEBGL_draw_buffers");f&&(b.drawBuffers=function(a,b){f.drawBuffersWEBGL(a,b)})}b.Fd=b.getExtension("EXT_disjoint_timer_query");var g="OES_texture_float OES_texture_half_float OES_standard_derivatives OES_vertex_array_object WEBGL_compressed_texture_s3tc WEBGL_depth_texture OES_element_index_uint EXT_texture_filter_anisotropic ANGLE_instanced_arrays OES_texture_float_linear OES_texture_half_float_linear WEBGL_compressed_texture_atc WEBKIT_WEBGL_compressed_texture_pvrtc WEBGL_compressed_texture_pvrtc EXT_color_buffer_half_float WEBGL_color_buffer_float EXT_frag_depth EXT_sRGB WEBGL_draw_buffers WEBGL_shared_resources EXT_shader_texture_lod EXT_color_buffer_float".split(" ");
(a=b.getSupportedExtensions())&&0<a.length&&b.getSupportedExtensions().forEach(function(a){-1!=g.indexOf(a)&&b.getExtension(a)})}}var pe,qe;function _glDrawElements(a,b,c,d){GLctx.drawElements(a,b,c,d)}
function re(a,b){if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 34814:case 36345:c=0;break;case 34466:c=GLctx.getParameter(34467).length;break;case 33309:if(2>GLctx.canvas.u.version){Z(1282);return}c=2*GLctx.getSupportedExtensions().length;break;case 33307:case 33308:if(2>GLctx.canvas.u.version){Z(1280);return}c=33307==a?3:0}if(void 0===c)switch(c=GLctx.getParameter(a),typeof c){case "number":break;case "boolean":c=c?1:0;break;case "string":Z(1280);return;case "object":if(null===
c)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 35097:case 36389:case 34068:c=0;break;default:Z(1280);return}else{if(c instanceof Float32Array||c instanceof Uint32Array||c instanceof Int32Array||c instanceof Array){for(a=0;a<c.length;++a)w[b+4*a>>2]=c[a];return}if(c instanceof WebGLBuffer||c instanceof WebGLProgram||c instanceof WebGLFramebuffer||c instanceof WebGLRenderbuffer||c instanceof WebGLQuery||c instanceof WebGLSampler||c instanceof WebGLSync||
c instanceof WebGLTransformFeedback||c instanceof WebGLVertexArrayObject||c instanceof WebGLTexture)c=c.name|0;else{Z(1280);return}}break;default:Z(1280);return}w[b>>2]=c}else Z(1281)}
function se(a,b,c,d,f){switch(b){case 6406:case 6409:case 6402:case 6403:case 36244:b=1;break;case 6410:case 33319:case 33320:b=2;break;case 6407:case 35904:case 36248:b=3;break;case 6408:case 35906:case 36249:b=4;break;default:return Z(1280),null}switch(a){case 5121:case 5120:var g=1*b;break;case 5123:case 36193:case 5131:case 5122:g=2*b;break;case 5125:case 5126:case 5124:g=4*b;break;case 34042:case 35902:case 33640:case 35899:case 34042:g=4;break;case 33635:case 32819:case 32820:g=2;break;default:return Z(1280),
null}b=fe;c*=g;b*=Math.floor((c+b-1)/b);d=0>=d?0:(d-1)*b+c;switch(a){case 5120:return oa.subarray(f,f+d);case 5121:return z.subarray(f,f+d);case 5122:return ua.subarray(f>>1,f+d>>1);case 5124:return w.subarray(f>>2,f+d>>2);case 5126:return C.subarray(f>>2,f+d>>2);case 5125:case 34042:case 35902:case 33640:case 35899:case 34042:return xa.subarray(f>>2,f+d>>2);case 5123:case 33635:case 32819:case 32820:case 36193:case 5131:return wa.subarray(f>>1,f+d>>1);default:return Z(1280),null}}
function te(a){switch(a){case 5120:return oa;case 5121:return z;case 5122:return ua;case 5123:case 33635:case 32819:case 32820:case 36193:case 5131:return wa;case 5124:return w;case 5125:case 34042:case 35902:case 33640:case 35899:case 34042:return xa;case 5126:return C;default:return null}}
function ue(a){switch(a){case 5120:case 5121:return 0;case 5122:case 5123:case 33635:case 32819:case 32820:case 36193:case 5131:return 1;case 5124:case 5126:case 5125:case 34042:case 35902:case 33640:case 35899:case 34042:return 2;default:return 0}}var ve={},we=1;function xe(a,b){xe.v||(xe.v={});a in xe.v||(e.dynCall_v(b),xe.v[a]=1)}oc();Ob=Array(4096);cc(H,"/");L("/tmp");L("/home");L("/home/web_user");
(function(){L("/dev");Ab(259,{read:function(){return 0},write:function(a,b,f,g){return g}});ec("/dev/null",259);zb(1280,Db);zb(1536,Eb);ec("/dev/tty",1280);ec("/dev/tty1",1536);if("undefined"!==typeof crypto){var a=new Uint8Array(1);var b=function(){crypto.getRandomValues(a);return a[0]}}else b=m?function(){return require("crypto").randomBytes(1)[0]}:function(){return 256*Math.random()|0};M("/dev","random",b);M("/dev","urandom",b);L("/dev/shm");L("/dev/shm/tmp")})();L("/proc");L("/proc/self");L("/proc/self/fd");
cc({m:function(){var a=Gb("/proc/self","fd",16895,73);a.c={lookup:function(a,c){var b=Mb[+c];if(!b)throw new G(E.ba);a={parent:null,m:{Qa:"fake"},c:{readlink:function(){return b.path}}};return a.parent=a}};return a}},"/proc/self/fd");
La.unshift(function(){if(!e.noFSInit&&!pc){assert(!pc,"FS.init was previously called. If you want to initialize later with custom parameters, remove any earlier calls (note that one is automatically added to the generated code)");pc=!0;oc();e.stdin=e.stdin;e.stdout=e.stdout;e.stderr=e.stderr;e.stdin?M("/dev","stdin",e.stdin):fc("/dev/tty","/dev/stdin");e.stdout?M("/dev","stdout",null,e.stdout):fc("/dev/tty","/dev/stdout");e.stderr?M("/dev","stderr",null,e.stderr):fc("/dev/tty1","/dev/stderr");var a=
jc("/dev/stdin","r");assert(0===a.fd,"invalid handle for stdin ("+a.fd+")");a=jc("/dev/stdout","w");assert(1===a.fd,"invalid handle for stdout ("+a.fd+")");a=jc("/dev/stderr","w");assert(2===a.fd,"invalid handle for stderr ("+a.fd+")")}});Ma.push(function(){Pb=!1});Na.push(function(){pc=!1;var a=e._fflush;a&&a(0);for(a=0;a<Mb.length;a++){var b=Mb[a];b&&lc(b)}});e.FS_createFolder=rc;e.FS_createPath=sc;e.FS_createDataFile=uc;e.FS_createPreloadedFile=yc;e.FS_createLazyFile=xc;e.FS_createLink=vc;
e.FS_createDevice=M;e.FS_unlink=hc;La.unshift(function(){});Na.push(function(){});if(m){var fs=require("fs"),Jb=require("path");J.zb()}m?Cc=function(){var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:"undefined"!==typeof dateNow?Cc=dateNow:"object"===typeof self&&self.performance&&"function"===typeof self.performance.now?Cc=function(){return self.performance.now()}:"object"===typeof performance&&"function"===typeof performance.now?Cc=function(){return performance.now()}:Cc=Date.now;
(function(){if("undefined"!==typeof window){window.addEventListener("gamepadconnected",function(){++Gc});window.addEventListener("gamepaddisconnected",function(){--Gc});var a=navigator.getGamepads?navigator.getGamepads():navigator.webkitGetGamepads?navigator.webkitGetGamepads():null;a&&(Gc=a.length)}})();e.requestFullScreen=function(a,b,c){e.printErr("Module.requestFullScreen is deprecated. Please call Module.requestFullscreen instead.");e.requestFullScreen=e.requestFullscreen;Pd(a,b,c)};
e.requestFullscreen=function(a,b,c){Ld(a,b,c)};e.requestAnimationFrame=function(a){Sd(a)};e.setCanvasSize=function(a,b,c){Nd(e.canvas,a,b);c||Md()};e.pauseMainLoop=function(){id=null;kd++};e.resumeMainLoop=function(){kd++;var a=nd,b=od,c=ld;ld=null;Vd(c,0,!1,md,!0);Ud(a,b);id()};e.getUserMedia=function(){window.getUserMedia||(window.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(void 0)};e.createContext=function(a,b,c,d){return Ed(a,b,c,d)};var GLctx;le=new Float32Array(256);
for(var ye=0;256>ye;ye++)me[ye]=le.subarray(0,ye+1);for(ye=0;32>ye;ye++)ee.push(Array(ye));Fa=ha(4);Aa=Ba=ja(r);Ca=Aa+Ia;Da=ja(Ca);w[Fa>>2]=Da;ia=!0;function Cb(a,b){var c=Array(ra(a)+1);a=B(a,c,0,c.length);b&&(c.length=a);return c}e.wasmTableSize=892;e.wasmMaxTableSize=892;e.bb={};
e.cb={abort:t,enlargeMemory:function(){Ga()},getTotalMemory:function(){return Ha},abortOnCannotGrowMemory:Ga,invoke_i:function(a){try{return e.dynCall_i(a)}catch(b){if("number"!==typeof b&&"longjmp"!==b)throw b;e.setThrew(1,0)}},invoke_ii:function(a,b){try{return e.dynCall_ii(a,b)}catch(c){if("number"!==typeof c&&"longjmp"!==c)throw c;e.setThrew(1,0)}},invoke_iii:function(a,b,c){try{return e.dynCall_iii(a,b,c)}catch(d){if("number"!==typeof d&&"longjmp"!==d)throw d;e.setThrew(1,0)}},invoke_vi:function(a,
b){try{e.dynCall_vi(a,b)}catch(c){if("number"!==typeof c&&"longjmp"!==c)throw c;e.setThrew(1,0)}},invoke_vii:function(a,b,c){try{e.dynCall_vii(a,b,c)}catch(d){if("number"!==typeof d&&"longjmp"!==d)throw d;e.setThrew(1,0)}},invoke_viii:function(a,b,c,d){try{e.dynCall_viii(a,b,c,d)}catch(f){if("number"!==typeof f&&"longjmp"!==f)throw f;e.setThrew(1,0)}},invoke_viiii:function(a,b,c,d,f){try{e.dynCall_viiii(a,b,c,d,f)}catch(g){if("number"!==typeof g&&"longjmp"!==g)throw g;e.setThrew(1,0)}},___cxa_allocate_exception:function(a){return u(a)},
___cxa_pure_virtual:function(){ma=!0;throw"Pure virtual function called!";},___cxa_throw:function(a){"uncaught_exception"in pb?pb.v++:pb.v=1;throw a+" - Exception catching is disabled, this exception cannot be caught. Compile with -s DISABLE_EXCEPTION_CATCHING=0 or DISABLE_EXCEPTION_CATCHING=2 to catch.";},___lock:function(){},___setErrNo:rb,___syscall140:function(a,b){N=b;try{var c=Bc();O();var d=O(),f=O(),g=O();mc(c,d,g);w[f>>2]=c.position;c.oa&&0===d&&0===g&&(c.oa=null);return 0}catch(h){return"undefined"!==
typeof FS&&h instanceof G||t(h),-h.D}},___syscall145:function(a,b){N=b;try{var c=Bc(),d=O();a:{var f=O();for(b=a=0;b<f;b++){var g=w[d+(8*b+4)>>2],h=c,q=w[d+8*b>>2],n=g,p=void 0,v=oa;if(0>n||0>p)throw new G(E.h);if(1===(h.flags&2097155))throw new G(E.ba);if(I(h.node.mode))throw new G(E.U);if(!h.f.read)throw new G(E.h);var y="undefined"!==typeof p;if(!y)p=h.position;else if(!h.seekable)throw new G(E.da);var Y=h.f.read(h,v,q,n,p);y||(h.position+=Y);var x=Y;if(0>x){var va=-1;break a}a+=x;if(x<g)break}va=
a}return va}catch(Ea){return"undefined"!==typeof FS&&Ea instanceof G||t(Ea),-Ea.D}},___syscall146:function(a,b){N=b;try{var c=Bc(),d=O();a:{var f=O();for(b=a=0;b<f;b++){var g=nc(c,oa,w[d+8*b>>2],w[d+(8*b+4)>>2],void 0);if(0>g){var h=-1;break a}a+=g}h=a}return h}catch(q){return"undefined"!==typeof FS&&q instanceof G||t(q),-q.D}},___syscall221:function(a,b){N=b;try{var c=Bc();switch(O()){case 0:var d=O();return 0>d?-E.h:jc(c.path,c.flags,0,d).fd;case 1:case 2:return 0;case 3:return c.flags;case 4:return d=
O(),c.flags|=d,0;case 12:case 12:return d=O(),ua[d+0>>1]=2,0;case 13:case 14:case 13:case 14:return 0;case 16:case 8:return-E.h;case 9:return rb(E.h),-1;default:return-E.h}}catch(f){return"undefined"!==typeof FS&&f instanceof G||t(f),-f.D}},___syscall5:function(a,b){N=b;try{var c=A(O()),d=O(),f=O();return jc(c,d,f).fd}catch(g){return"undefined"!==typeof FS&&g instanceof G||t(g),-g.D}},___syscall54:function(a,b){N=b;try{var c=Bc(),d=O();switch(d){case 21509:case 21505:return c.tty?0:-E.K;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return c.tty?
0:-E.K;case 21519:if(!c.tty)return-E.K;var f=O();return w[f>>2]=0;case 21520:return c.tty?-E.h:-E.K;case 21531:a=f=O();if(!c.f.qb)throw new G(E.K);return c.f.qb(c,d,a);case 21523:return c.tty?0:-E.K;default:t("bad ioctl syscall "+d)}}catch(g){return"undefined"!==typeof FS&&g instanceof G||t(g),-g.D}},___syscall6:function(a,b){N=b;try{var c=Bc();lc(c);return 0}catch(d){return"undefined"!==typeof FS&&d instanceof G||t(d),-d.D}},___unlock:function(){},_abort:function(){e.abort()},_clock_gettime:function(a,
b){if(0===a)a=Date.now();else if(1===a&&(m||"undefined"!==typeof dateNow||(ba||l)&&self.performance&&self.performance.now))a=Cc();else return rb(E.h),-1;w[b>>2]=a/1E3|0;w[b+4>>2]=a%1E3*1E6|0;return 0},_emscripten_enter_soft_fullscreen:function(a,b){a||(a="#canvas");a=R(a);if(!a)return-4;var c={};c.S=w[b>>2];c.N=w[b+4>>2];c.Ha=w[b+8>>2];c.l=w[b+12>>2];c.M=w[b+16>>2];c.target=a;c.Wa=!0;var d=bd(a,c);document.documentElement.style.overflow="hidden";document.body.scroll="no";document.body.style.margin=
"0px";var f=dd(a);ed=function(){d();for(var a=0;a<f.length;++a)f[a].node.style.display=f[a].jb;window.removeEventListener("resize",fd);c.l&&e.dynCall_iiii(c.l,37,0,c.M)};T=c;window.addEventListener("resize",fd);c.l&&e.dynCall_iiii(c.l,37,0,c.M);return 0},_emscripten_exit_fullscreen:function(){if("undefined"===typeof Zc())return-1;for(var a=Pc,b=0;b<S.length;++b)S[b].ua==a&&(S.splice(b,1),--b);if(document.exitFullscreen)document.exitFullscreen();else if(document.msExitFullscreen)document.msExitFullscreen();
else if(document.mozCancelFullScreen)document.mozCancelFullScreen();else if(document.webkitExitFullscreen)document.webkitExitFullscreen();else return-1;T.l&&e.dynCall_iiii(T.l,37,0,T.M);return 0},_emscripten_exit_soft_fullscreen:function(){ed&&ed();ed=null;return 0},_emscripten_get_canvas_element_size:function(a,b,c){a=a?R(a):e.canvas;if(!a)return-4;w[b>>2]=a.width;w[c>>2]=a.height;return 0},_emscripten_get_element_css_size:function(a,b,c){a=a?R(a):e.canvas;if(!a)return-4;a.getBoundingClientRect?
(a=a.getBoundingClientRect(),D[b>>3]=a.right-a.left,D[c>>3]=a.bottom-a.top):(D[b>>3]=a.clientWidth,D[c>>3]=a.clientHeight);return 0},_emscripten_get_fullscreen_status:function(a){if("undefined"===typeof Zc())return-1;$c(a);return 0},_emscripten_longjmp:function(a,b){gd(a,b)},_emscripten_memcpy_big:function(a,b,c){z.set(z.subarray(b,b+c),a);return a},_emscripten_request_fullscreen:function(a,b){var c={S:0,N:0,Ha:0};c.ib=b;return hd(a,c)},_emscripten_set_click_callback:function(a,b,c,d){Xc(a,b,c,d,
4,"click");return 0},_emscripten_set_dblclick_callback:function(a,b,c,d){Xc(a,b,c,d,7,"dblclick");return 0},_emscripten_set_fullscreenchange_callback:function(a,b,c,d){if("undefined"===typeof Zc())return-1;if(a){if(a=R(a),!a)return-4}else a=document;ad(a,b,c,d,"fullscreenchange");ad(a,b,c,d,"mozfullscreenchange");ad(a,b,c,d,"webkitfullscreenchange");ad(a,b,c,d,"msfullscreenchange");return 0},_emscripten_set_keydown_callback:function(a,b,c,d){Vc(a,b,c,d,2,"keydown");return 0},_emscripten_set_keypress_callback:function(a,
b,c,d){Vc(a,b,c,d,1,"keypress");return 0},_emscripten_set_keyup_callback:function(a,b,c,d){Vc(a,b,c,d,3,"keyup");return 0},_emscripten_set_main_loop:Vd,_emscripten_set_mousedown_callback:function(a,b,c,d){Xc(a,b,c,d,5,"mousedown");return 0},_emscripten_set_mousemove_callback:function(a,b,c,d){Xc(a,b,c,d,8,"mousemove");return 0},_emscripten_set_mouseup_callback:function(a,b,c,d){Xc(a,b,c,d,6,"mouseup");return 0},_emscripten_set_touchcancel_callback:function(a,b,c,d){cd(a,b,c,d,25,"touchcancel");return 0},
_emscripten_set_touchend_callback:function(a,b,c,d){cd(a,b,c,d,23,"touchend");return 0},_emscripten_set_touchmove_callback:function(a,b,c,d){cd(a,b,c,d,24,"touchmove");return 0},_emscripten_set_touchstart_callback:function(a,b,c,d){cd(a,b,c,d,22,"touchstart");return 0},_emscripten_set_wheel_callback:function(a,b,c,d){a=R(a);return"undefined"!==typeof a.onwheel?(Yc(a,b,c,d,"wheel"),0):"undefined"!==typeof a.onmousewheel?(Yc(a,b,c,d,"mousewheel"),0):-1},_emscripten_webgl_create_context:function(a,b){var c=
{};c.alpha=!!w[b>>2];c.depth=!!w[b+4>>2];c.stencil=!!w[b+8>>2];c.antialias=!!w[b+12>>2];c.premultipliedAlpha=!!w[b+16>>2];c.preserveDrawingBuffer=!!w[b+20>>2];c.preferLowPowerToHighPerformance=!!w[b+24>>2];c.failIfMajorPerformanceCaveat=!!w[b+28>>2];c.majorVersion=w[b+32>>2];c.minorVersion=w[b+36>>2];c.explicitSwapControl=w[b+44>>2];a=(a=A(a))&&"#canvas"!==a||!e.canvas?be[a]||R(a):e.canvas.id?be[e.canvas.id]||R(e.canvas.id):e.canvas;return a?c.explicitSwapControl?(console.error("emscripten_webgl_create_context failed: explicitSwapControl is not supported, please rebuild with -s OFFSCREENCANVAS_SUPPORT=1 to enable targeting the experimental OffscreenCanvas specification!"),
0):Fd(a,c):0},_emscripten_webgl_enable_extension:function(a,b){a=Gd[a];b=A(b);0==b.indexOf("GL_")&&(b=b.substr(3));return a.GLctx.getExtension(b)?1:0},_emscripten_webgl_init_context_attributes:function(a){w[a>>2]=1;w[a+4>>2]=1;w[a+8>>2]=0;w[a+12>>2]=1;w[a+16>>2]=1;w[a+20>>2]=0;w[a+24>>2]=0;w[a+28>>2]=0;w[a+32>>2]=1;w[a+36>>2]=0;w[a+40>>2]=1;w[a+44>>2]=0},_emscripten_webgl_make_context_current:function(a){return Hd(a)?0:-5},_glActiveTexture:function(a){GLctx.activeTexture(a)},_glAttachShader:function(a,
b){GLctx.attachShader(U[a],W[b])},_glBindBuffer:function(a,b){var c=b?Yd[b]:null;35051==a?GLctx.Ed=b:35052==a&&(GLctx.hb=b);GLctx.bindBuffer(a,c)},_glBindFramebuffer:function(a,b){GLctx.bindFramebuffer(a,b?Zd[b]:null)},_glBindTexture:function(a,b){GLctx.bindTexture(a,b?ae[b]:null)},_glBlendFunc:function(a,b){GLctx.blendFunc(a,b)},_glBufferData:function(a,b,c,d){c?X.B?GLctx.bufferData(a,z,d,c,b):GLctx.bufferData(a,z.subarray(c,c+b),d):GLctx.bufferData(a,b,d)},_glCheckFramebufferStatus:function(a){return GLctx.checkFramebufferStatus(a)},
_glClear:function(a){GLctx.clear(a)},_glClearColor:function(a,b,c,d){GLctx.clearColor(a,b,c,d)},_glClearDepthf:function(a){GLctx.clearDepth(a)},_glClearStencil:function(a){GLctx.clearStencil(a)},_glColorMask:function(a,b,c,d){GLctx.colorMask(!!a,!!b,!!c,!!d)},_glCompileShader:function(a){GLctx.compileShader(W[a])},_glCreateProgram:function(){var a=ke(U),b=GLctx.createProgram();b.name=a;U[a]=b;return a},_glCreateShader:function(a){var b=ke(W);W[b]=GLctx.createShader(a);return b},_glCullFace:function(a){GLctx.cullFace(a)},
_glDeleteBuffers:function(a,b){for(var c=0;c<a;c++){var d=w[b+4*c>>2],f=Yd[d];f&&(GLctx.deleteBuffer(f),f.name=0,Yd[d]=null,d==pe&&(pe=0),d==qe&&(qe=0))}},_glDeleteProgram:function(a){if(a){var b=U[a];b?(GLctx.deleteProgram(b),b.name=0,U[a]=null,ce[a]=null):Z(1281)}},_glDeleteShader:function(a){if(a){var b=W[a];b?(GLctx.deleteShader(b),W[a]=null):Z(1281)}},_glDeleteTextures:function(a,b){for(var c=0;c<a;c++){var d=w[b+4*c>>2],f=ae[d];f&&(GLctx.deleteTexture(f),f.name=0,ae[d]=null)}},_glDepthFunc:function(a){GLctx.depthFunc(a)},
_glDepthMask:function(a){GLctx.depthMask(!!a)},_glDepthRangef:function(a,b){GLctx.depthRange(a,b)},_glDisable:function(a){GLctx.disable(a)},_glDisableVertexAttribArray:function(a){GLctx.disableVertexAttribArray(a)},_glDrawElements:_glDrawElements,_glEnable:function(a){GLctx.enable(a)},_glEnableVertexAttribArray:function(a){GLctx.enableVertexAttribArray(a)},_glFramebufferRenderbuffer:function(a,b,c,d){GLctx.framebufferRenderbuffer(a,b,c,$d[d])},_glFramebufferTexture2D:function(a,b,c,d,f){GLctx.framebufferTexture2D(a,
b,c,ae[d],f)},_glFrontFace:function(a){GLctx.frontFace(a)},_glGenBuffers:function(a,b){for(var c=0;c<a;c++){var d=GLctx.createBuffer();if(!d){for(Z(1282);c<a;)w[b+4*c++>>2]=0;break}var f=ke(Yd);d.name=f;Yd[f]=d;w[b+4*c>>2]=f}},_glGenTextures:function(a,b){for(var c=0;c<a;c++){var d=GLctx.createTexture();if(!d){for(Z(1282);c<a;)w[b+4*c++>>2]=0;break}var f=ke(ae);d.name=f;ae[f]=d;w[b+4*c>>2]=f}},_glGenerateMipmap:function(a){GLctx.generateMipmap(a)},_glGetActiveAttrib:function(a,b,c,d,f,g,h){a=U[a];
if(a=GLctx.getActiveAttrib(a,b))0<c&&h?(c=B(a.name,z,h,c),d&&(w[d>>2]=c)):d&&(w[d>>2]=0),f&&(w[f>>2]=a.size),g&&(w[g>>2]=a.type)},_glGetActiveUniform:function(a,b,c,d,f,g,h){a=U[a];if(a=GLctx.getActiveUniform(a,b))0<c&&h?(c=B(a.name,z,h,c),d&&(w[d>>2]=c)):d&&(w[d>>2]=0),f&&(w[f>>2]=a.size),g&&(w[g>>2]=a.type)},_glGetAttribLocation:function(a,b){a=U[a];b=A(b);return GLctx.getAttribLocation(a,b)},_glGetIntegerv:function(a,b){re(a,b)},_glGetProgramInfoLog:function(a,b,c,d){a=GLctx.getProgramInfoLog(U[a]);
null===a&&(a="(unknown error)");0<b&&d?(b=B(a,z,d,b),c&&(w[c>>2]=b)):c&&(w[c>>2]=0)},_glGetProgramiv:function(a,b,c){if(c)if(a>=Wd)Z(1281);else{var d=ce[a];if(d)if(35716==b)a=GLctx.getProgramInfoLog(U[a]),null===a&&(a="(unknown error)"),w[c>>2]=a.length+1;else if(35719==b)w[c>>2]=d.qa;else if(35722==b){if(-1==d.X){a=U[a];var f=GLctx.getProgramParameter(a,GLctx.ACTIVE_ATTRIBUTES);for(b=d.X=0;b<f;++b)d.X=Math.max(d.X,GLctx.getActiveAttrib(a,b).name.length+1)}w[c>>2]=d.X}else if(35381==b){if(-1==d.Y)for(a=
U[a],f=GLctx.getProgramParameter(a,GLctx.Cb),b=d.Y=0;b<f;++b){var g=GLctx.Id(a,b);d.Y=Math.max(d.Y,g.length+1)}w[c>>2]=d.Y}else w[c>>2]=GLctx.getProgramParameter(U[a],b);else Z(1282)}else Z(1281)},_glGetShaderInfoLog:function(a,b,c,d){a=GLctx.getShaderInfoLog(W[a]);null===a&&(a="(unknown error)");0<b&&d?(b=B(a,z,d,b),c&&(w[c>>2]=b)):c&&(w[c>>2]=0)},_glGetShaderiv:function(a,b,c){c?35716==b?(a=GLctx.getShaderInfoLog(W[a]),null===a&&(a="(unknown error)"),w[c>>2]=a.length+1):35720==b?(a=GLctx.getShaderSource(W[a]),
w[c>>2]=null===a||0==a.length?0:a.length+1):w[c>>2]=GLctx.getShaderParameter(W[a],b):Z(1281)},_glGetString:function(a){if(de[a])return de[a];switch(a){case 7936:case 7937:case 37445:case 37446:var b=na(Cb(GLctx.getParameter(a)));break;case 7938:b=GLctx.getParameter(GLctx.VERSION);b=2<=GLctx.canvas.u.version?"OpenGL ES 3.0 ("+b+")":"OpenGL ES 2.0 ("+b+")";b=na(Cb(b));break;case 7939:b=GLctx.getSupportedExtensions();for(var c=[],d=0;d<b.length;++d)c.push(b[d]),c.push("GL_"+b[d]);b=na(Cb(c.join(" ")));
break;case 35724:b=GLctx.getParameter(GLctx.SHADING_LANGUAGE_VERSION);c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=na(Cb(b));break;default:return Z(1280),0}return de[a]=b},_glGetUniformLocation:function(a,b){b=A(b);var c=0;if(-1!==b.indexOf("]",b.length-1)){var d=b.lastIndexOf("["),f=b.slice(d+1,-1);if(0<f.length&&(c=parseInt(f),0>c))return-1;b=b.slice(0,d)}a=ce[a];return a?(b=a.Xa[b])&&c<b[0]?b[1]+c:-1:
-1},_glHint:function(a,b){GLctx.hint(a,b)},_glLinkProgram:function(a){GLctx.linkProgram(U[a]);ce[a]=null;var b=U[a];ce[a]={Xa:{},qa:0,X:-1,Y:-1};a=ce[a];for(var c=a.Xa,d=GLctx.getProgramParameter(b,GLctx.ACTIVE_UNIFORMS),f=0;f<d;++f){var g=GLctx.getActiveUniform(b,f),h=g.name;a.qa=Math.max(a.qa,h.length+1);-1!==h.indexOf("]",h.length-1)&&(h=h.slice(0,h.lastIndexOf("[")));var q=GLctx.getUniformLocation(b,h);if(null!=q){var n=ke(V);c[h]=[g.size,n];V[n]=q;for(var p=1;p<g.size;++p)q=GLctx.getUniformLocation(b,
h+"["+p+"]"),n=ke(V),V[n]=q}}},_glPixelStorei:function(a,b){3333==a||3317==a&&(fe=b);GLctx.pixelStorei(a,b)},_glPolygonOffset:function(a,b){GLctx.polygonOffset(a,b)},_glScissor:function(a,b,c,d){GLctx.scissor(a,b,c,d)},_glShaderSource:function(a,b,c,d){for(var f="",g=0;g<b;++g){if(d){var h=w[d+4*g>>2];h=0>h?A(w[c+4*g>>2]):A(w[c+4*g>>2],h)}else h=A(w[c+4*g>>2]);f+=h}GLctx.shaderSource(W[a],f)},_glStencilFunc:function(a,b,c){GLctx.stencilFunc(a,b,c)},_glStencilMask:function(a){GLctx.stencilMask(a)},
_glStencilOp:function(a,b,c){GLctx.stencilOp(a,b,c)},_glTexParameterf:function(a,b,c){GLctx.texParameterf(a,b,c)},_glTexParameteri:function(a,b,c){GLctx.texParameteri(a,b,c)},_glTexStorage2D:function(a,b,c,d,f){GLctx.texStorage2D(a,b,c,d,f)},_glTexSubImage2D:function(a,b,c,d,f,g,h,q,n){if(X.B)GLctx.hb?GLctx.texSubImage2D(a,b,c,d,f,g,h,q,n):0!=n?GLctx.texSubImage2D(a,b,c,d,f,g,h,q,te(q),n>>ue(q)):GLctx.texSubImage2D(a,b,c,d,f,g,h,q,null);else{var p=null;n&&(p=se(q,h,f,g,n));GLctx.texSubImage2D(a,b,
c,d,f,g,h,q,p)}},_glUniform1fv:function(a,b,c){if(X.B)GLctx.uniform1fv(V[a],C,c>>2,b);else{if(256>=b){var d=me[b-1];for(var f=0;f<b;++f)d[f]=C[c+4*f>>2]}else d=C.subarray(c>>2,c+4*b>>2);GLctx.uniform1fv(V[a],d)}},_glUniform1i:function(a,b){GLctx.uniform1i(V[a],b)},_glUniform2fv:function(a,b,c){if(X.B)GLctx.uniform2fv(V[a],C,c>>2,2*b);else{if(256>=2*b){var d=me[2*b-1];for(var f=0;f<2*b;f+=2)d[f]=C[c+4*f>>2],d[f+1]=C[c+(4*f+4)>>2]}else d=C.subarray(c>>2,c+8*b>>2);GLctx.uniform2fv(V[a],d)}},_glUniform3fv:function(a,
b,c){if(X.B)GLctx.uniform3fv(V[a],C,c>>2,3*b);else{if(256>=3*b){var d=me[3*b-1];for(var f=0;f<3*b;f+=3)d[f]=C[c+4*f>>2],d[f+1]=C[c+(4*f+4)>>2],d[f+2]=C[c+(4*f+8)>>2]}else d=C.subarray(c>>2,c+12*b>>2);GLctx.uniform3fv(V[a],d)}},_glUniform4fv:function(a,b,c){if(X.B)GLctx.uniform4fv(V[a],C,c>>2,4*b);else{if(256>=4*b){var d=me[4*b-1];for(var f=0;f<4*b;f+=4)d[f]=C[c+4*f>>2],d[f+1]=C[c+(4*f+4)>>2],d[f+2]=C[c+(4*f+8)>>2],d[f+3]=C[c+(4*f+12)>>2]}else d=C.subarray(c>>2,c+16*b>>2);GLctx.uniform4fv(V[a],d)}},
_glUniformMatrix2fv:function(a,b,c,d){if(X.B)GLctx.uniformMatrix2fv(V[a],!!c,C,d>>2,4*b);else{if(256>=4*b){var f=me[4*b-1];for(var g=0;g<4*b;g+=4)f[g]=C[d+4*g>>2],f[g+1]=C[d+(4*g+4)>>2],f[g+2]=C[d+(4*g+8)>>2],f[g+3]=C[d+(4*g+12)>>2]}else f=C.subarray(d>>2,d+16*b>>2);GLctx.uniformMatrix2fv(V[a],!!c,f)}},_glUniformMatrix3fv:function(a,b,c,d){if(X.B)GLctx.uniformMatrix3fv(V[a],!!c,C,d>>2,9*b);else{if(256>=9*b){var f=me[9*b-1];for(var g=0;g<9*b;g+=9)f[g]=C[d+4*g>>2],f[g+1]=C[d+(4*g+4)>>2],f[g+2]=C[d+
(4*g+8)>>2],f[g+3]=C[d+(4*g+12)>>2],f[g+4]=C[d+(4*g+16)>>2],f[g+5]=C[d+(4*g+20)>>2],f[g+6]=C[d+(4*g+24)>>2],f[g+7]=C[d+(4*g+28)>>2],f[g+8]=C[d+(4*g+32)>>2]}else f=C.subarray(d>>2,d+36*b>>2);GLctx.uniformMatrix3fv(V[a],!!c,f)}},_glUniformMatrix4fv:function(a,b,c,d){if(X.B)GLctx.uniformMatrix4fv(V[a],!!c,C,d>>2,16*b);else{if(256>=16*b){var f=me[16*b-1];for(var g=0;g<16*b;g+=16)f[g]=C[d+4*g>>2],f[g+1]=C[d+(4*g+4)>>2],f[g+2]=C[d+(4*g+8)>>2],f[g+3]=C[d+(4*g+12)>>2],f[g+4]=C[d+(4*g+16)>>2],f[g+5]=C[d+(4*
g+20)>>2],f[g+6]=C[d+(4*g+24)>>2],f[g+7]=C[d+(4*g+28)>>2],f[g+8]=C[d+(4*g+32)>>2],f[g+9]=C[d+(4*g+36)>>2],f[g+10]=C[d+(4*g+40)>>2],f[g+11]=C[d+(4*g+44)>>2],f[g+12]=C[d+(4*g+48)>>2],f[g+13]=C[d+(4*g+52)>>2],f[g+14]=C[d+(4*g+56)>>2],f[g+15]=C[d+(4*g+60)>>2]}else f=C.subarray(d>>2,d+64*b>>2);GLctx.uniformMatrix4fv(V[a],!!c,f)}},_glUseProgram:function(a){GLctx.useProgram(a?U[a]:null)},_glVertexAttribIPointer:function(a,b,c,d,f){GLctx.Pd(a,b,c,d,f)},_glVertexAttribPointer:function(a,b,c,d,f,g){GLctx.vertexAttribPointer(a,
b,c,!!d,f,g)},_glViewport:function(a,b,c,d){GLctx.viewport(a,b,c,d)},_llvm_trap:function(){t("trap!")},_longjmp:gd,_pthread_getspecific:function(a){return ve[a]||0},_pthread_key_create:function(a){if(0==a)return E.h;w[a>>2]=we;ve[we]=0;we++;return 0},_pthread_mutex_destroy:function(){},_pthread_once:xe,_pthread_setspecific:function(a,b){if(!(a in ve))return E.h;ve[a]=b;return 0},DYNAMICTOP_PTR:Fa,STACKTOP:Ba};var ze=e.asm(e.bb,e.cb,buffer);e.asm=ze;
var nb=e.__GLOBAL__sub_I_free_camera_cpp=function(){return e.asm.__GLOBAL__sub_I_free_camera_cpp.apply(null,arguments)},jb=e.__GLOBAL__sub_I_gfx_camera_cpp=function(){return e.asm.__GLOBAL__sub_I_gfx_camera_cpp.apply(null,arguments)},Ya=e.__GLOBAL__sub_I_gfx_cpp=function(){return e.asm.__GLOBAL__sub_I_gfx_cpp.apply(null,arguments)},Za=e.__GLOBAL__sub_I_gfx_material_cpp=function(){return e.asm.__GLOBAL__sub_I_gfx_material_cpp.apply(null,arguments)},kb=e.__GLOBAL__sub_I_gfx_quad_2d_cpp=function(){return e.asm.__GLOBAL__sub_I_gfx_quad_2d_cpp.apply(null,
arguments)},$a=e.__GLOBAL__sub_I_gfx_rt_cpp=function(){return e.asm.__GLOBAL__sub_I_gfx_rt_cpp.apply(null,arguments)},lb=e.__GLOBAL__sub_I_gfx_scene_cpp=function(){return e.asm.__GLOBAL__sub_I_gfx_scene_cpp.apply(null,arguments)},ab=e.__GLOBAL__sub_I_gfx_shader_cpp=function(){return e.asm.__GLOBAL__sub_I_gfx_shader_cpp.apply(null,arguments)},db=e.__GLOBAL__sub_I_gfx_surface_cpp=function(){return e.asm.__GLOBAL__sub_I_gfx_surface_cpp.apply(null,arguments)},bb=e.__GLOBAL__sub_I_gfx_tex_cpp=function(){return e.asm.__GLOBAL__sub_I_gfx_tex_cpp.apply(null,
arguments)},cb=e.__GLOBAL__sub_I_gfx_util_cpp=function(){return e.asm.__GLOBAL__sub_I_gfx_util_cpp.apply(null,arguments)},mb=e.__GLOBAL__sub_I_gfx_vxo_cpp=function(){return e.asm.__GLOBAL__sub_I_gfx_vxo_cpp.apply(null,arguments)},Xa=e.__GLOBAL__sub_I_input_ctrl_cpp=function(){return e.asm.__GLOBAL__sub_I_input_ctrl_cpp.apply(null,arguments)},ob=e.__GLOBAL__sub_I_transitions_cpp=function(){return e.asm.__GLOBAL__sub_I_transitions_cpp.apply(null,arguments)},eb=e.__GLOBAL__sub_I_unit_cpp=function(){return e.asm.__GLOBAL__sub_I_unit_cpp.apply(null,
arguments)},fb=e.__GLOBAL__sub_I_unit_techno_globe_cpp=function(){return e.asm.__GLOBAL__sub_I_unit_techno_globe_cpp.apply(null,arguments)},hb=e.__GLOBAL__sub_I_ux_camera_cpp=function(){return e.asm.__GLOBAL__sub_I_ux_camera_cpp.apply(null,arguments)},ib=e.__GLOBAL__sub_I_ux_com_cpp=function(){return e.asm.__GLOBAL__sub_I_ux_com_cpp.apply(null,arguments)},gb=e.__GLOBAL__sub_I_ux_cpp=function(){return e.asm.__GLOBAL__sub_I_ux_cpp.apply(null,arguments)};
e.___errno_location=function(){return e.asm.___errno_location.apply(null,arguments)};e._main=function(){return e.asm._main.apply(null,arguments)};var u=e._malloc=function(){return e.asm._malloc.apply(null,arguments)};e.setThrew=function(){return e.asm.setThrew.apply(null,arguments)};var ta=e.stackAlloc=function(){return e.asm.stackAlloc.apply(null,arguments)};e.dynCall_i=function(){return e.asm.dynCall_i.apply(null,arguments)};e.dynCall_ii=function(){return e.asm.dynCall_ii.apply(null,arguments)};
e.dynCall_iii=function(){return e.asm.dynCall_iii.apply(null,arguments)};e.dynCall_iiii=function(){return e.asm.dynCall_iiii.apply(null,arguments)};e.dynCall_v=function(){return e.asm.dynCall_v.apply(null,arguments)};e.dynCall_vi=function(){return e.asm.dynCall_vi.apply(null,arguments)};e.dynCall_vii=function(){return e.asm.dynCall_vii.apply(null,arguments)};e.dynCall_viii=function(){return e.asm.dynCall_viii.apply(null,arguments)};
e.dynCall_viiii=function(){return e.asm.dynCall_viiii.apply(null,arguments)};e.asm=ze;e.getMemory=function(a){if(ia)if(Pa)var b=u(a);else{assert(Fa);b=w[Fa>>2];a=b+a+15&-16;w[Fa>>2]=a;if(a=a>=Ha)Ga(),a=!0;a&&(w[Fa>>2]=b,b=0)}else b=ha(a);return b};e.addRunDependency=Ua;e.removeRunDependency=Va;e.FS_createFolder=rc;e.FS_createPath=sc;e.FS_createDataFile=uc;e.FS_createPreloadedFile=yc;e.FS_createLazyFile=xc;e.FS_createLink=vc;e.FS_createDevice=M;e.FS_unlink=hc;
function fa(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}fa.prototype=Error();fa.prototype.constructor=fa;Ta=function Ae(){e.calledRun||Be();e.calledRun||(Ta=Ae)};
e.callMain=function(a){a=a||[];Pa||(Pa=!0,Ja(La));var b=a.length+1,c=ta(4*(b+1));w[c>>2]=sa(e.thisProgram);for(var d=1;d<b;d++)w[(c>>2)+d]=sa(a[d-1]);w[(c>>2)+b]=0;try{var f=e._main(b,c,0);Ce(f,!0)}catch(g){g instanceof fa||("SimulateInfiniteLoop"==g?e.noExitRuntime=!0:((a=g)&&"object"===typeof g&&g.stack&&(a=[g,g.stack]),e.printErr("exception thrown: "+a),e.quit(1,g)))}finally{}};
function Be(a){function b(){if(!e.calledRun&&(e.calledRun=!0,!ma)){Pa||(Pa=!0,Ja(La));Ja(Ma);if(e.onRuntimeInitialized)e.onRuntimeInitialized();e._main&&De&&e.callMain(a);if(e.postRun)for("function"==typeof e.postRun&&(e.postRun=[e.postRun]);e.postRun.length;){var b=e.postRun.shift();Oa.unshift(b)}Ja(Oa)}}a=a||e.arguments;if(!(0<Ra)){if(e.preRun)for("function"==typeof e.preRun&&(e.preRun=[e.preRun]);e.preRun.length;)Qa();Ja(Ka);0<Ra||e.calledRun||(e.setStatus?(e.setStatus("Running..."),setTimeout(function(){setTimeout(function(){e.setStatus("")},
1);b()},1)):b())}}e.run=Be;function Ce(a,b){if(!b||!e.noExitRuntime||0!==a){if(!e.noExitRuntime&&(ma=!0,Ba=void 0,Ja(Na),e.onExit))e.onExit(a);m&&process.exit(a);e.quit(a,new fa(a))}}e.exit=Ce;function t(a){if(e.onAbort)e.onAbort(a);void 0!==a?(e.print(a),e.printErr(a),a=JSON.stringify(a)):a="";ma=!0;throw"abort("+a+"). Build with -s ASSERTIONS=1 for more info.";}e.abort=t;if(e.preInit)for("function"==typeof e.preInit&&(e.preInit=[e.preInit]);0<e.preInit.length;)e.preInit.pop()();var De=!0;
e.noInitialRun&&(De=!1);e.noExitRuntime=!0;Be();
